Repository youtube/cobalt, pull requests merged in 2023-08, with the labels that each got.

#500 Add ${test}_evergreen_loader targets for all gtests
  starboard/build/config/BUILDCONFIG.gn
  starboard/elf_loader/BUILD.gn
  starboard/loader_app/BUILD.gn
Labels: on_device

#1052 Large scale change: pre-commit checks vol9
  .pre-commit-config.yaml
  starboard/android/shared/decode_target_create.cc
  starboard/android/shared/decode_target_internal.h
  starboard/android/shared/egl_swap_buffers.cc
  starboard/android/shared/file_internal.cc
  starboard/android/shared/jni_env_ext_test.cc
  starboard/android/shared/log_flush.cc
  starboard/android/shared/sanitizer_options.cc
  starboard/android/shared/speech_synthesis_internal.cc
  starboard/android/shared/system_network_is_disconnected.cc
  starboard/android/shared/system_platform_error.cc
  starboard/android/shared/thread_get_name.cc
  starboard/egl.h
  starboard/gles.h
  starboard/loader_app/drain_file_helper.h
  starboard/loader_app/installation_manager_test.cc
  starboard/nplb/align_test.cc
  starboard/nplb/condition_variable_wait_timed_test.cc
  starboard/nplb/configuration_test.cc
  starboard/nplb/file_delete_recursive_test.cc
  starboard/nplb/file_helpers.cc
  starboard/nplb/file_write_test.cc
  starboard/nplb/image_test.cc
  starboard/nplb/include_all_too.c
  starboard/nplb/murmurhash2_test.cc
  starboard/nplb/semaphore_test.cc
  starboard/nplb/string_compare_no_case_n_test.cc
  starboard/nplb/thread_join_test.cc
  starboard/nplb/thread_local_value_test.cc
  starboard/nplb/thread_sleep_test.cc
  starboard/once.h
Labels: on_device

#805 Re-enable test 'CallThisPointerIsNullRainyDay'
  starboard/android/shared/platform_configuration/BUILD.gn
  starboard/android/shared/test_filters.py
Labels: on_device

#1112 Revert "Re-enable black_box_test framework on Android arm"
  cobalt/black_box_tests/black_box_tests.py
  starboard/android/arm/cobalt/configuration.py
Labels: on_device

#1078 Move `ref_counted` and `rect` to glimp
  glimp/BUILD.gn
  glimp/gles/buffer.h
  glimp/gles/context.h
  glimp/gles/draw_state.h
  glimp/gles/framebuffer.h
  glimp/gles/pixel_format.h
  glimp/gles/program.h
  glimp/gles/program_impl.h
  glimp/gles/ref_counted_resource_map.h
  glimp/gles/renderbuffer.h
  glimp/gles/resource_manager.h
  glimp/gles/sampler.h
  glimp/gles/shader.h
  glimp/gles/texture.cc
  glimp/gles/texture.h
  glimp/gles/texture_impl.h
  glimp/polymorphic_downcast.h
  glimp/rect.h
  glimp/ref_counted.cc
  glimp/ref_counted.h
  glimp/stub/egl/get_proc_address_impl.cc
  glimp/stub/egl/pbuffer_surface_impl.h
  glimp/stub/gles/buffer_impl.h
  glimp/stub/gles/context_impl.cc
  glimp/stub/gles/program_impl.cc
  glimp/stub/gles/program_impl.h
  glimp/stub/gles/shader_impl.h
  glimp/stub/gles/texture_impl.cc
  glimp/stub/gles/texture_impl.h
  glimp/thread_collision_warner.cc
  glimp/thread_collision_warner.h
  nb/BUILD.gn
Labels: on_device

#1049 Add LTS Nightly Omaha product to evergreen updater.
  cobalt/updater/configurator.cc
  cobalt/updater/configurator.h
  cobalt/updater/configurator_test.cc
  components/update_client/component.cc
  components/update_client/persisted_data.cc
  components/update_client/persisted_data.h
Labels: cp-24.lts.1+

#1152 [android] Replace SB_CHECK() with SB_LOG(WARNING)
  starboard/android/shared/video_decoder.cc
Labels: cp-24.lts.1+

#1140 Add CSS parsing histograms
  cobalt/dom/html_link_element.cc
  cobalt/dom/html_style_element.cc
Labels: cp-24.lts.1+

#1159 Disable SbAudioSinkTest.ContinuousAppend on Android
  starboard/android/shared/test_filters.py
Labels: on_device

#1125 Remove starboard:gn_all dep on crashpad/handler
  starboard/BUILD.gn
Labels: on_device

#1172 Bound set_scroll_* functions
  cobalt/dom/html_element.cc
Labels: cp-24.lts.1+

#1183 Remove cruft log
  cobalt/dom/html_element.cc
Labels: cp-24.lts.1+

#1216 Move BidirectionalReuseAllocator
  cobalt/media/BUILD.gn
  cobalt/media/bidirectional_fit_reuse_allocator.cc
  cobalt/media/bidirectional_fit_reuse_allocator.h
  cobalt/media/bidirectional_fit_reuse_allocator_test.cc
  cobalt/media/decoder_buffer_allocator.cc
  cobalt/media/decoder_buffer_allocator.h
  nb/BUILD.gn
  nb/memory_pool.h
Labels: on_device

#1222 Move StarboardAllocator
  cobalt/media/BUILD.gn
  cobalt/media/bidirectional_fit_reuse_allocator_test.cc
  cobalt/media/decoder_buffer_allocator.h
  cobalt/media/starboard_memory_allocator.h
  nb/BUILD.gn
  nb/first_fit_reuse_allocator_test.cc
  nb/fixed_no_free_allocator_test.cc
  nb/starboard_aligned_memory_deleter.h
Labels: runtest, on_device

#1225 Final move of remaining nb/ parts to starboard/common
  cobalt/build/cobalt_configuration.py
  cobalt/media/BUILD.gn
  cobalt/media/bidirectional_fit_reuse_allocator.cc
  cobalt/media/bidirectional_fit_reuse_allocator.h
  cobalt/media/bidirectional_fit_reuse_allocator_test.cc
  cobalt/media/decoder_buffer_allocator.cc
  cobalt/media/starboard_memory_allocator.h
  glimp/BUILD.gn
  glimp/gles/context.cc
  glimp/gles/texture.cc
  glimp/stub/egl/pbuffer_surface_impl.cc
  nb/.gitignore
  nb/BUILD.gn
  nb/README.md
  nb/first_fit_reuse_allocator.cc
  nb/first_fit_reuse_allocator.h
  nb/first_fit_reuse_allocator_test.cc
  nb/reuse_allocator_benchmark.cc
  nb/run_all_unittests.cc
  nb/testdata/mem_history_cobalt.txt
  nb/testdata/mem_history_gpu.txt
  nb/testdata/mem_history_main.txt
  starboard/common/BUILD.gn
  starboard/common/allocator.cc
  starboard/common/allocator.h
  starboard/common/fixed_no_free_allocator.cc
  starboard/common/fixed_no_free_allocator.h
  starboard/common/fixed_no_free_allocator_test.cc
  starboard/common/memory_pool.h
  starboard/common/pointer_arithmetic.h
  starboard/common/reuse_allocator_base.cc
  starboard/common/reuse_allocator_base.h
Labels: on_device

#1177 Introduce `cast_starboard_api`.
  .github/config/linux-modular.json
  starboard/BUILD.gn
  starboard/build/config/starboard_target_type.gni
  starboard/contrib/cast/README.md
  starboard/contrib/cast/cast.gni
  starboard/contrib/cast/cast_starboard_api/samples/BUILD.gn
  starboard/contrib/cast/cast_starboard_api/samples/cast_starboard_api.lds
  starboard/contrib/cast/cast_starboard_api/samples/cast_starboard_api_test.cc
  starboard/shared/x11/application_x11.cc
Labels: outside collaborator

#1115 Refine timestamp calculation in AudioResamplerImpl
  starboard/shared/starboard/player/filter/audio_resampler_impl.cc
  starboard/shared/starboard/player/filter/testing/BUILD.gn
  starboard/shared/starboard/player/filter/testing/adaptive_audio_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/audio_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/audio_resampler_test.cc
Labels: cp-24.lts.1+

#1335 Docker Compose V2 and related build fixes
  .github/actions/docker/action.yaml
  .github/actions/docker_win/action.yaml
  AUTHORS
  CONTRIBUTING.md
  cobalt/doc/docker_build.md
  cobalt/site/docs/development/setup-docker.md
  cobalt/site/docs/gen/cobalt/doc/docker_build.md
  docker-compose-windows-internal.yml
  docker-compose.yml
  docker/docsite/README.md
  docker/linux/base/Dockerfile
  docker/linux/base/build/Dockerfile
  docker/linux/unittest/unittest_docker_launcher.py
Labels: outside collaborator

#1386 Write environment variables to unique file for msvc toolchain
  build/toolchain/win/msvc_toolchain.gni
Labels: on_device

#1422 [nplb] Relax SbMediaGetAudioConfiguration() to 3 ms
  starboard/nplb/media_configuration_test.cc
Labels: on_device

#1424 Extend raspi pexpect timeout
  starboard/raspi/shared/launcher.py
Labels: on_device

#1433 Generate debug info for non CI builds or qa, gold builds
  starboard/xb1/platform_configuration/BUILD.gn
Labels: cp-24.lts.1+

#1425 Move retry logic to individual readline calls
  starboard/raspi/shared/launcher.py
Labels: on_device
