Repository youtube/cobalt, pull requests merged in 2023-12, with the labels that each got.

#2040 Rename global variable in eztime
  starboard/client_porting/eztime/eztime.cc
Labels: runtest, cp-24.lts.1+

#2043 Make run_all_unittests a source_set
  base/test/BUILD.gn
Labels: runtest

#2133 Fix build break for OTS and reduce Starboardization
  third_party/ots/BUILD.gn
  third_party/ots/include/config.h
  third_party/ots/include/opentype-sanitiser.h
  third_party/ots/include/ots-memory-stream.h
  third_party/ots/src/cff.cc
  third_party/ots/src/cmap.cc
  third_party/ots/src/name.cc
  third_party/ots/src/ots.h
Labels: on_device

#2140 Android blacboxtests fix, workaround for Python webdriver
  cobalt/tools/automated_testing/cobalt_runner.py
Labels: on_device
