Repository youtube/cobalt, pull requests merged in 2023-04, with the labels that each got.

#45 Get build number from commit count
  .github/workflows/main.yaml
  .github/workflows/main_win.yaml
  cobalt/build/get_build_id.py
  docker/linux/clang-3-9/Dockerfile
  docker/linux/gcc-6-3/Dockerfile
Labels: ready to pull

#84 Revert "Create marker commit"
  file_marker.txt
Labels: ready to pull

#69 Filter flaky Semaphore.ThreadTakesWait_TimeExpires on win32
  starboard/win/win32/test_filters.py
Labels: ready to pull

#62 Test external change
  README.md
Labels: ready to pull

#101 Revert "Test external change"
  README.md
Labels: ready to pull

#103 Update README.md
  README.md
Labels: ready to pull

#106 Fix up retry logic in Raspi launcher
  starboard/raspi/shared/launcher.py
Labels: on_device, runtest, ready to pull

#123 Use search for multiline re string
  cobalt/build/get_build_id.py
Labels: ready to pull

#139 Disable support for last access time in the cookie store.
  net/cookies/cookie_monster_unittest.cc
  net/cookies/cookie_options.cc
  net/cookies/cookie_options.h
Labels: ready to pull

#155 Add failure detection, logging for expect dialogue
  starboard/evergreen/testing/raspi-2/secure_communication.sh
Labels: on_device

#153 Device type test
  cobalt/browser/application.cc
  starboard/android/shared/system_get_property.cc
  starboard/common/BUILD.gn
  starboard/common/device_type.cc
  starboard/common/device_type.h
  starboard/linux/x64x11/system_get_property_impl.cc
  starboard/nplb/system_get_property_test.cc
  starboard/raspi/shared/system_get_property.cc
  starboard/shared/uwp/application_uwp.cc
  starboard/shared/uwp/player_components_factory.cc
  starboard/shared/uwp/system_get_property.cc
  starboard/shared/win32/system_get_property.cc
Labels: ready to pull

#119 Refactor Raspi launcher
  starboard/raspi/shared/launcher.py
  starboard/raspi/shared/launcher_test.py
  starboard/raspi/shared/retry.py
  starboard/raspi/shared/retry_test.py
Labels: on_device, runtest

#167 Clean up unused tests configuration code
  cobalt/build/cobalt_configuration.py
  cobalt/site/docs/gen/starboard/doc/building.md
  cobalt/tools/webdriver_benchmark_config.py
  starboard/android/shared/cobalt/configuration.py
  starboard/build/application_configuration.py
  starboard/contrib/linux/stadia/gyp_configuration.py
  starboard/doc/building.md
  starboard/evergreen/arm/shared/cobalt/configuration.py
  starboard/evergreen/x64/cobalt/configuration.py
  starboard/linux/shared/cobalt/configuration.py
  starboard/raspi/shared/cobalt/configuration.py
  starboard/win/win32/cobalt/configuration.py
Labels: on_device

#161 Use repo vars to control ODT execution
  .github/workflows/main.yaml
Labels: on_device

#171 Revert "Revert "Cherry pick PR #119: Refactor Raspi launcher""
  starboard/raspi/shared/launcher.py
  starboard/raspi/shared/launcher_test.py
  starboard/raspi/shared/retry.py
  starboard/raspi/shared/retry_test.py
Labels: on_device

#179 [linux] Re-enable VideoDecoder invalid data tests
  starboard/linux/shared/test_filters.py
Labels: ready to pull

#186 Revert "Revert "Cherry pick PR #119: Refactor Raspi launcher"" (#171)
  starboard/raspi/shared/launcher.py
  starboard/raspi/shared/launcher_test.py
  starboard/raspi/shared/retry.py
  starboard/raspi/shared/retry_test.py
Labels: on_device, runtest

#189 Change CSP warning messages from DLOG to LOG.
  cobalt/web/csp_delegate.cc
  cobalt/worker/service_worker_object.cc
Labels: cp-23.lts.1+

#191 Disable flaky nplb test on Evergreen
  starboard/evergreen/shared/gyp_configuration.py
Labels: on_device
