Repository youtube/cobalt, pull requests merged in 2023-05, with the labels that each got.

#183 [android] Fix e/ac3 sync frame parsing issue
  starboard/android/shared/audio_renderer_passthrough.cc
Labels: ready to pull

#214 Re-enable Evergreen tests
  starboard/evergreen/testing/run_all_tests.sh
Labels: on_device

#216 Run on device tests on nightly workflows
  .github/workflows/main.yaml
Labels: on_device

#249 Cherry pick PR #183: [android] Fix e/ac3 sync frame parsing issue
  starboard/android/shared/audio_renderer_passthrough.cc
Labels: ready to pull

#260 Turn ANRs for offloaded SourceBuffer to crash
  cobalt/dom/serialized_algorithm_runner.h
Labels: ready to pull

#203 Add on-device test retries for android and raspi
  .github/actions/on_device_tests/action.yaml
  .github/config/android-arm.json
  .github/config/android-arm64.json
  .github/config/android-x86.json
  .github/config/evergreen-arm-hardfp.json
  .github/config/raspi-2.json
  .github/workflows/main.yaml
  tools/on_device_tests_gateway.proto
  tools/on_device_tests_gateway_client.py
Labels: on_device

#290 Add unit tests for api leak detector
  starboard/tools/api_leak_detector/api_leak_detector.py
  starboard/tools/api_leak_detector/api_leak_detector_test.py
Labels: ready to pull

#307 [media] Refactor OutputModeSupported()
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/player_get_preferred_output_mode.cc
  starboard/linux/shared/player_components_factory.cc
  starboard/raspi/shared/player_components_factory.cc
  starboard/shared/starboard/player/filter/player_components.h
  starboard/shared/starboard/player/filter/testing/player_components_test.cc
  starboard/shared/starboard/player/filter/testing/test_util.cc
  starboard/shared/starboard/player/filter/testing/video_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/video_decoder_test_fixture.cc
  starboard/shared/starboard/player/filter/video_decoder_internal.h
  starboard/shared/starboard/player/player_get_preferred_output_mode_prefer_punchout.cc
  starboard/shared/uwp/player_components_factory.cc
  starboard/shared/win32/player_components_factory.cc
Labels: ready to pull

#334 Run get_build_id from file dir
  cobalt/build/get_build_id.py
Labels: ready to pull

#323 [media] Update heaac.dmp
  starboard/shared/starboard/player/testdata/heaac.dmp.sha1
Labels: ready to pull

#156 [android] Fix ANR on MediaCapabilitiesCache reload
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
  starboard/android/shared/media_capabilities_cache.cc
  starboard/android/shared/media_capabilities_cache.h
Labels: ready to pull

#373 [android] Refine Widevine L3 implementation
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaDrmBridge.java
  starboard/android/shared/BUILD.gn
  starboard/android/shared/drm_create_system.cc
  starboard/android/shared/drm_system.cc
  starboard/android/shared/drm_system.h
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_common.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_is_supported.cc
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/video_decoder.cc
Labels: ready to pull

#343 Remove deprecated build number server functions
  cobalt/build/build_number.py
  cobalt/build/get_build_id.py
  cobalt/build/save_build_id.py
Labels: ready to pull

#339 Remove unused platform defaults
  starboard/tools/build.py
  starboard/tools/command_line.py
  starboard/tools/command_line_test.py
Labels: on_device, ready to pull

#423 Add NPLB test files for new secondary decoder requirements
  starboard/shared/starboard/player/testdata/beneath_the_canopy_135_avc.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_136_avc.dmp.sha1
  starboard/shared/starboard/player/testdata/sha1_files.gni
Labels: ready to pull

#122 [media] Add SbPlayer tests with drm system
  starboard/evergreen/x64/test_filters.py
  starboard/nplb/drm_helpers.h
  starboard/nplb/player_test_fixture.cc
  starboard/nplb/player_test_fixture.h
  starboard/nplb/player_test_util.cc
  starboard/nplb/player_test_util.h
  starboard/nplb/player_write_sample_test.cc
  starboard/win/win32/test_filters.py
Labels: ready to pull

#441 Add missing C++ 17 new/delete align symbols.
  starboard/common/new.cc
Labels: on_device, runtest

#444 [loader] Add debugging code for FetcherCache crash
  cobalt/loader/fetcher_cache.cc
  cobalt/loader/fetcher_cache.h
  cobalt/loader/loader_factory.cc
  cobalt/loader/loader_factory.h
Labels: ready to pull

#468 Fix Evergreen API leaks for arm64.
  third_party/llvm-project/compiler-rt/BUILD.gn
Labels: ready to pull

#470 Add missing Evergreen-arm64 builds
  .github/config/evergreen-arm64.json
  .github/workflows/evergreen.yaml
  third_party/llvm-project/compiler-rt/BUILD.gn
Labels: on_device, ready to pull

#476 Add args for launching blackboxtests for specific test set
  .github/actions/on_host_test/action.yaml
  .github/config/evergreen-x64.json
  .github/config/linux-clang-3-9.json
  .github/config/linux.json
  cobalt/black_box_tests/black_box_tests.py
  tools/create_archive.py
Labels: on_device, runtest, ready to pull
