Repository youtube/cobalt, pull requests merged in 2023-11, with the labels that each got.

#1890 Create MicCreationSuccessful UMA histogram
  cobalt/media_capture/media_devices.cc
  tools/metrics/histograms/metadata/cobalt/histograms.xml
Labels: runtest, outside collaborator

#1889 Use installable lib as Evergreen loader's data dep
  starboard/build/config/BUILDCONFIG.gn
Labels: on_device

#1892 Remove --no-install-recommends and patcher from Android Dockerfile
  docker/linux/android/Dockerfile
Labels: on_device

#1843 Prevent a high CPU usage if tunnel mode is enabled
  starboard/android/shared/media_decoder.cc
Labels: outside collaborator

#1901 Place app_launcher files in folder in out dir
  starboard/tools/BUILD.gn
  starboard/tools/app_launcher_packager.py
Labels: on_device

#1473 Rename libstarboard_platform_group.so to libstarboard.so.{sb_version}
  base/BUILD.gn
  cobalt/base/BUILD.gn
  cobalt/browser/BUILD.gn
  cobalt/debug/BUILD.gn
  cobalt/h5vcc/BUILD.gn
  cobalt/input/BUILD.gn
  cobalt/media/BUILD.gn
  cobalt/media/sandbox/BUILD.gn
  cobalt/media_capture/BUILD.gn
  cobalt/media_stream/BUILD.gn
  cobalt/renderer/BUILD.gn
  cobalt/speech/BUILD.gn
  cobalt/subtlecrypto/BUILD.gn
  cobalt/updater/BUILD.gn
  cobalt/websocket/BUILD.gn
  cobalt/xhr/BUILD.gn
  content/browser/speech/BUILD.gn
  crypto/BUILD.gn
  net/BUILD.gn
  starboard/BUILD.gn
  starboard/android/shared/BUILD.gn
  starboard/benchmark/BUILD.gn
  starboard/build/config/BUILDCONFIG.gn
  starboard/build/config/starboard_target_type.gni
  starboard/build/install/install_target.gni
  starboard/client_porting/cwrappers/BUILD.gn
  starboard/client_porting/eztime/BUILD.gn
  starboard/client_porting/poem/BUILD.gn
  starboard/contrib/cast/README.md
  starboard/contrib/cast/cast_starboard_api/samples/BUILD.gn
  starboard/elf_loader/BUILD.gn
  starboard/examples/glclear/BUILD.gn
  starboard/examples/hello_world/BUILD.gn
  starboard/examples/window/BUILD.gn
  starboard/extension/BUILD.gn
  starboard/loader_app/BUILD.gn
  starboard/nplb/BUILD.gn
  starboard/nplb/compiler_compliance/BUILD.gn
  starboard/nplb/nplb_evergreen_compat_tests/BUILD.gn
  starboard/raspi/shared/install_target.gni
  starboard/shared/ffmpeg/BUILD.gn
  starboard/shared/starboard/player/filter/testing/BUILD.gn
  starboard/xb1/shared/BUILD.gn
  third_party/QR-Code-generator/BUILD.gn
  third_party/chromium/media/BUILD.gn
  third_party/crashpad/handler/BUILD.gn
  third_party/crashpad/tools/BUILD.gn
  third_party/googletest/BUILD.gn
Labels: on_device

#1951 Use Locale for android String.format
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaDrmBridge.java
Labels: cp-24.lts.1+, on_device

#1910 Support live streams (ie big timestamps), replace float with double
  cobalt/dom/html_media_element.cc
  cobalt/dom/html_media_element.h
  cobalt/media/player/web_media_player.h
  cobalt/media/player/web_media_player_impl.cc
  cobalt/media/player/web_media_player_impl.h
  cobalt/media/sandbox/web_media_player_helper.cc
  cobalt/media/sandbox/web_media_player_sandbox.cc
  cobalt/media_session/media_session_client.cc
Labels: outside collaborator
