Repository youtube/cobalt, pull requests merged in 2023-06, with the labels that each got.

#508 Limit heap arenas on glibc
  starboard/linux/x64x11/main.cc
Labels: on_device

#521 Revert "Enable Java unit test coverage report"
  starboard/android/apk/app/build.gradle
  starboard/android/apk/build.gradle
  starboard/android/apk/gradle/wrapper/gradle-wrapper.properties
Labels: on_device

#519 Fix a rare crash in custom_event
  cobalt/web/custom_event.h
Labels: on_device

#517 Remove unused ResourceContext and TextureDataPBO.
  cobalt/renderer/backend/egl/BUILD.gn
  cobalt/renderer/backend/egl/graphics_context.cc
  cobalt/renderer/backend/egl/graphics_context.h
  cobalt/renderer/backend/egl/graphics_system.cc
  cobalt/renderer/backend/egl/graphics_system.h
  cobalt/renderer/backend/egl/resource_context.cc
  cobalt/renderer/backend/egl/resource_context.h
  cobalt/renderer/backend/egl/texture.cc
  cobalt/renderer/backend/egl/texture_data_pbo.cc
  cobalt/renderer/backend/egl/texture_data_pbo.h
  cobalt/renderer/rasterizer/skia/hardware_mesh.cc
  cobalt/renderer/rasterizer/skia/hardware_mesh.h
Labels: on_device

#525 Pin Choco to 1.4.0
  docker/windows/base/build/Dockerfile
Labels: ready to pull

#435 [nplb] Add tests for SbPlayerGetAudioConfiguration
  starboard/android/shared/test_filters.py
  starboard/android/x86/test_filters.py
  starboard/evergreen/x64/test_filters.py
  starboard/nplb/BUILD.gn
  starboard/nplb/player_get_audio_configuration_test.cc
  starboard/nplb/player_test_fixture.cc
  starboard/nplb/player_test_fixture.h
  starboard/nplb/player_test_util.cc
  starboard/nplb/player_test_util.h
  starboard/nplb/player_write_sample_test.cc
  starboard/player.h
  starboard/raspi/shared/test_filters.py
  starboard/win/win32/test_filters.py
Labels: ready to pull

#532 Run presubmit workflows on draft PRs.
  .github/workflows/android.yaml
  .github/workflows/evergreen.yaml
  .github/workflows/linux.yaml
  .github/workflows/main.yaml
  .github/workflows/main_win.yaml
  .github/workflows/raspi-2.yaml
  .github/workflows/stub.yaml
  .github/workflows/win32.yaml
Labels: on_device, runtest

#535 Move SbPlayerPipeline declaration to .h file
  cobalt/media/BUILD.gn
  cobalt/media/base/pipeline.h
  cobalt/media/base/sbplayer_pipeline.cc
  cobalt/media/base/sbplayer_pipeline.h
  cobalt/media/player/web_media_player_impl.cc
Labels: ready to pull

#549 Run on-device test on PRs without label.
  .github/workflows/main.yaml
Labels: runtest

#631 Revert "Add a timeout to postBlockingTask()"
  base/single_thread_task_runner.cc
Labels: on_device

#632 Revert "Cherry pick PR #554: Add a timeout to postBlockingTask()"
  base/single_thread_task_runner.cc
Labels: on_device

#629 Remove Android internal input_events_filter
  starboard/android/shared/BUILD.gn
  starboard/android/shared/application_android.cc
  starboard/android/shared/application_android.h
Labels: on_device

#627 23.lts.1+ service worker cherry-picks
  cobalt/layout_tests/testdata/web-platform-tests/service-workers/web_platform_tests.txt
  cobalt/worker/service_worker_jobs.cc
  third_party/web_platform_tests/service-workers/service-worker/registration-service-worker-attributes.https.html
  third_party/web_platform_tests/service-workers/service-worker/resources/test-helpers.sub.js
  third_party/web_platform_tests/service-workers/service-worker/update-no-cache-request-headers.https.html
Labels: on_device

#621 Cleaning up Starboardizations from BoringSSL
  third_party/boringssl/src/ssl/ssl_buffer.cc
Labels: on_device

#673 Disable PixelTest.TooManyGlyphs on Android
  starboard/android/shared/cobalt/configuration.py
Labels: on_device

#653 Merge V8 version 8.8.278.17
  third_party/v8/METADATA
  third_party/v8/include/v8-version.h
  third_party/v8/infra/testing/PRESUBMIT.py
  third_party/v8/infra/testing/builders.pyl
  third_party/v8/src/common/message-template.h
  third_party/v8/src/compiler/backend/ia32/code-generator-ia32.cc
  third_party/v8/src/compiler/operator-properties.cc
  third_party/v8/src/compiler/simd-scalar-lowering.cc
  third_party/v8/src/deoptimizer/deoptimizer.cc
  third_party/v8/src/flags/flag-definitions.h
  third_party/v8/src/interpreter/bytecode-generator.cc
  third_party/v8/src/objects/value-serializer.cc
  third_party/v8/src/wasm/baseline/liftoff-assembler.cc
  third_party/v8/src/wasm/baseline/liftoff-compiler.cc
  third_party/v8/test/mjsunit/mjsunit.status
  third_party/v8/test/mjsunit/regress/regress-1161357.js
  third_party/v8/test/mjsunit/regress/regress-crbug-1038178.js
  third_party/v8/test/mjsunit/regress/regress-crbug-1171954.js
  third_party/v8/test/mjsunit/regress/wasm/regress-1161654.js
  third_party/v8/test/mjsunit/wasm/worker-memory.js
Labels: on_device

#688 Disable Android-arm64 crashing lottie test
  starboard/android/arm64/cobalt/__init__.py
  starboard/android/arm64/cobalt/configuration.py
Labels: on_device

#634 Partially Revert PR#554 and only leave the part of adding logging
  base/single_thread_task_runner.cc
Labels: on_device

#683 [nplb] Filter vertical video test on android x86
  starboard/android/x86/test_filters.py
Labels: on_device

#685 Creates build_info.json alongside cobalt_build_id.
  cobalt/browser/BUILD.gn
  cobalt/build/BUILD.gn
  cobalt/build/build_info.py
  cobalt/build/get_build_id.py
  cobalt/build/get_build_id_test.py
Labels: cp-23.lts.1+, cp-24.lts.1+

#713 Fix crash in net fetcher
  net/url_request/url_fetcher_core.cc
  net/url_request/url_fetcher_core.h
Labels: runtest, on_device

#717 Enable CRX file unit tests for Evergreen builds
  components/crx_file/BUILD.gn
  components/crx_file/crx_verifier_unittest.cc
  components/crx_file/testdata/sha1_files.gni
  components/crx_file/testdata/unsigned.crx3.sha1
  components/crx_file/testdata/valid.crx2.sha1
  components/crx_file/testdata/valid_no_publisher.crx3.sha1
  components/crx_file/testdata/valid_publisher.crx3.sha1
  components/crx_file/testdata/valid_test_publisher.crx3.sha1
  starboard/evergreen/shared/gyp_configuration.py
Labels: runtest
