Repository youtube/cobalt, pull requests merged in 2023-09, with the labels that each got.

#1434 [android] Refine dumpAllDecoders()
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecCapabilitiesLogger.java
Labels: on_device

#1461 [android] Allow to enable tunnel mode via mime attributes
  starboard/android/shared/player_components_factory.h
Labels: cp-24.lts.1+

#1492 Remove obsolete comment about ClientId
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
Labels: cp-24.lts.1+

#1489 Don't use starboard_platform_group install target for bundled platforms
  starboard/build/config/BUILDCONFIG.gn
  starboard/raspi/2/platform_configuration/configuration.gni
Labels: runtest, on_device

#1439 Attempt to resolve some dangling pointer issues in Telemetry
  cobalt/browser/metrics/cobalt_metrics_log_uploader.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_services_manager.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager.h
  cobalt/h5vcc/h5vcc_metrics.cc
  cobalt/h5vcc/h5vcc_metrics.h
Labels: cp-24.lts.1+

#1501 Strip raspi builds in CI
  starboard/raspi/shared/install_target.gni
Labels: on_device

#1509 Fix xml regex
  .pre-commit-config.yaml
Labels: runtest, cp-24.lts.1+

#1493 Remove special case for raspi-2 modular build.
  starboard/shared/ffmpeg/BUILD.gn
Labels: on_device

#1490 Remove raspi-2 -fno-exception hack.
  build/config/compiler/BUILD.gn
  starboard/nplb/BUILD.gn
  starboard/raspi/shared/platform_configuration/configuration.gni
  third_party/llvm-project/libcxxabi/BUILD.gn
Labels: on_device

#1544 Revert "Remove raspi-2 -fno-exception hack. (#1490)"
  build/config/compiler/BUILD.gn
  starboard/nplb/BUILD.gn
  starboard/raspi/shared/platform_configuration/configuration.gni
  third_party/llvm-project/libcxxabi/BUILD.gn
Labels: on_device

#1541 Separate modular configs from evergreen
  starboard/build/config/modular/BUILD.gn
  starboard/evergreen/shared/platform_configuration/BUILD.gn
  starboard/evergreen/shared/platform_configuration/configuration.gni
Labels: on_device

#1554 Remove exceptions from libcxxabi and nplb
  starboard/nplb/BUILD.gn
  third_party/llvm-project/libcxxabi/BUILD.gn
Labels: on_device

#901 Stop free scrolling on app hide
  cobalt/browser/BUILD.gn
  cobalt/browser/browser_module.cc
  cobalt/browser/browser_module.h
  cobalt/browser/splash_screen.h
  cobalt/dom/html_element.cc
  cobalt/layout/topmost_event_target.cc
  cobalt/ui_navigation/scroll_engine/scroll_engine.cc
  cobalt/ui_navigation/scroll_engine/scroll_engine.h
Labels: cp-24.lts.1+

#1555 Android TestRunner remove the old package before installation.
  starboard/android/shared/launcher.py
Labels: on_device

#1566 Remove raspi2 exception hack
  build/config/compiler/BUILD.gn
  starboard/raspi/shared/platform_configuration/BUILD.gn
  starboard/raspi/shared/platform_configuration/configuration.gni
Labels: on_device

#1487 Filter intermittent blackbox test cases
  starboard/android/arm/cobalt/configuration.py
Labels: on_device

#1615 Add SetTimeZone API as a starboard extension
  starboard/extension/extension_test.cc
  starboard/extension/time_zone.h
  starboard/linux/shared/BUILD.gn
  starboard/linux/shared/system_get_extensions.cc
  starboard/linux/shared/time_zone.cc
  starboard/linux/shared/time_zone.h
  starboard/nplb/time_zone_get_current_test.cc
Labels: on_device

#1588 Create MUSL specific-rename of finalize and atexit
  third_party/musl/src/exit/atexit.c
Labels: on_device

#1614 Update games-activity to version 2.0.2.
  starboard/android/apk/app/src/main/java/dev/cobalt/libraries/game_activity/games-activity-1.2.2.aar
  starboard/android/apk/app/src/main/java/dev/cobalt/libraries/game_activity/games-activity-2.0.2.aar
  starboard/android/shared/BUILD.gn
Labels: on_device
