Repository youtube/cobalt, pull requests merged in 2023-07, with the labels that each got.

#808 Add comment about async behavior of metrics APIs
  cobalt/h5vcc/h5vcc_metrics.idl
Labels: cp-24.lts.1+

#792 Add subfolder for drain_file_test
  starboard/loader_app/drain_file_test.cc
Labels: on_device

#828 Remove cpu-features dependency on Android
  starboard/android/shared/BUILD.gn
Labels: on_device

#827 Embed license text in binary
  cobalt/browser/BUILD.gn
  cobalt/dom/BUILD.gn
  cobalt/dom/navigator.cc
Labels: runtest, on_device

#638 Don't construct the StorageManager when not needed.
  cobalt/browser/application.cc
  cobalt/network/network_module.cc
  cobalt/network/network_module.h
  cobalt/storage/storage_manager.cc
  cobalt/storage/storage_manager.h
Labels: on_device

#835 Add starboardized CPU detection to WebP
  third_party/libwebp/BUILD.gn
  third_party/libwebp/src/dsp/cpu.c
Labels: on_device

#530 Enable Java unit test coverage report
  starboard/android/apk/app/build.gradle
  starboard/android/apk/build.gradle
  starboard/android/apk/gradle/wrapper/gradle-wrapper.properties
Labels: on_device

#851 Fix a deadlock in IsAnyClientUsingRegistration
  cobalt/worker/service_worker_context.cc
Labels: cp-24.lts.1+

#857 Remove reverse deps from Android Starboard code
  starboard/android/shared/android_media_session_client.cc
  starboard/android/shared/system_get_property.cc
  starboard/shared/stub/accessibility_get_caption_settings.cc
Labels: on_device

#847 Simplify worker_tools
  tools/create_archive.py
  tools/worker_tools.py
Labels: on_device

#907 Adds Cobalt Version to build info.
  cobalt/build/build_info.py
Labels: cp-23.lts.1+, cp-24.lts.1+

#932 Use clang++ front end for linking Evergreen builds.
  build/toolchain/gcc_toolchain.gni
  starboard/build/config/BUILDCONFIG.gn
  starboard/build/toolchain/BUILD.gn
  starboard/build/toolchain/linux/BUILD.gn
  starboard/evergreen/arm/hardfp/platform_configuration/BUILD.gn
  starboard/evergreen/arm/hardfp/toolchain/BUILD.gn
  starboard/evergreen/arm/softfp/platform_configuration/BUILD.gn
  starboard/evergreen/arm/softfp/toolchain/BUILD.gn
  starboard/evergreen/arm64/platform_configuration/BUILD.gn
  starboard/evergreen/arm64/toolchain/BUILD.gn
  starboard/evergreen/shared/platform_configuration/BUILD.gn
  starboard/evergreen/x64/platform_configuration/BUILD.gn
  starboard/evergreen/x64/toolchain/BUILD.gn
  starboard/evergreen/x86/platform_configuration/BUILD.gn
  starboard/evergreen/x86/toolchain/BUILD.gn
Labels: on_device

#970 Add some INFO logging to telemetry
  cobalt/browser/application.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager.cc
Labels: cp-24.lts.1+

#935 Simplify PersistentSetting initialization.
  cobalt/persistent_storage/persistent_settings.cc
  cobalt/persistent_storage/persistent_settings.h
Labels: on_device

#982 [android] Log the value of unknown status
  starboard/android/shared/media_decoder.cc
Labels: runtest, on_device

#986 Add missing test targets
  cobalt/build/cobalt_configuration.py
  cobalt/media/file_data_source_test.cc
  cobalt/renderer/test/png_utils/BUILD.gn
  starboard/build/platform_configuration.py
  starboard/win/win32/cobalt/configuration.py
Labels: on_device

#993 Use native_target/crashpad_handler in builds+tests
  .github/actions/build/action.yaml
  starboard/BUILD.gn
  starboard/evergreen/shared/launcher.py
  starboard/tools/testing/test_runner.py
  tools/create_archive.py
Labels: runtest

#963 [android] Support decode to texture for Shorts
  cobalt/media/base/sbplayer_bridge.cc
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/BUILD.gn
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/player_get_preferred_output_mode.cc
  starboard/android/shared/player_get_preferred_output_mode_test.cc
  starboard/android/shared/video_decoder.cc
  starboard/android/shared/video_decoder.h
  starboard/nplb/BUILD.gn
  starboard/nplb/drm_helpers.h
  starboard/shared/starboard/drm/drm_test_helpers.cc
  starboard/shared/starboard/drm/drm_test_helpers.h
Labels: runtest, on_device

#1002 Replace SetAllowCodeGenerationFromStringsCallback
  cobalt/script/v8c/v8c_global_environment.cc
  cobalt/script/v8c/v8c_global_environment.h
Labels: runtest, on_device

#1017 Disable failing Android media tests
  starboard/android/shared/test_filters.py
Labels: on_device

#1005 Add extra initialization and checks to worker
  cobalt/worker/worker.cc
  cobalt/worker/worker.h
Labels: on_device

#1009 Remove constant #ifdef of version compatibility
  cobalt/base/BUILD.gn
  cobalt/base/version_compatibility.cc
  cobalt/base/version_compatibility.h
  cobalt/browser/application.cc
  cobalt/cssom/selector_tree.cc
  cobalt/cssom/selector_tree.h
  cobalt/dom/document.cc
Labels: on_device

#1015 Large scale change: pre-commit checks vol5
  starboard/android/apk/app/src/app/java/dev/cobalt/app/CobaltApplication.java
  starboard/android/apk/app/src/main/java/dev/cobalt/account/AccessToken.java
  starboard/android/apk/app/src/main/java/dev/cobalt/account/UserAuthorizer.java
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/AdvertisingId.java
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/CobaltA11yHelper.java
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/CobaltService.java
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/ErrorDialog.java
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/NetworkStatus.java
  starboard/android/apk/app/src/main/java/dev/cobalt/media/CaptionSettings.java
  starboard/android/apk/app/src/main/java/dev/cobalt/media/Log.java
  starboard/android/apk/app/src/main/java/dev/cobalt/storage/CobaltStorageLoader.java
  starboard/android/apk/app/src/main/java/dev/cobalt/util/SystemPropertiesHelper.java
Labels: on_device

#1014 Large scale change: pre-commit checks vol4
  cobalt/cssom/css.idl
  cobalt/dom/device_orientation_event_init.idl
  cobalt/dom/dom_rect_read_only.idl
  cobalt/dom/history.idl
  cobalt/dom/mime_type_array.idl
  cobalt/dom/performance_observer_callback_options.idl
  cobalt/dom/plugin_array.idl
  cobalt/dom/wheel_event.idl
  cobalt/media_integration_tests/endurance/endurance_test.py
  cobalt/renderer/rasterizer/testdata/hunter_gone_too_deep.json
  cobalt/renderer/rasterizer/testdata/white_material_wave_loading.json
  cobalt/renderer/rasterizer/testdata/ytk_ink_logo_rotate.json
  cobalt/tools/collectd/install.sh
  starboard/android/apk/app/src/main/java/dev/cobalt/storage/README.md
  starboard/client_porting/README.md
  starboard/raspi/2/skia/platform_configuration/BUILD.gn
  starboard/shared/starboard/player/testdata/beneath_the_canopy_248_vp9.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_aac_5_1.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_aac_mono.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_aac_stereo.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_opus_5_1.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_opus_mono.dmp.sha1
  starboard/shared/starboard/player/testdata/beneath_the_canopy_opus_stereo.dmp.sha1
  starboard/shared/starboard/player/testdata/black_test_avc_1080p_30to60_fps.dmp.sha1
  starboard/shared/starboard/player/testdata/sintel_399_av1.dmp.sha1
  starboard_configuration.py
Labels: on_device

#1054 Fix telemetry proto payload deserialization
  cobalt/browser/metrics/cobalt_metrics_log_uploader.cc
  cobalt/browser/metrics/cobalt_metrics_log_uploader_test.cc
  cobalt/h5vcc/h5vcc_metric_type.idl
  cobalt/h5vcc/h5vcc_metrics.idl
Labels: cp-24.lts.1+

#1036 Increase sleep to address Watchdog test flakiness.
  cobalt/watchdog/watchdog_test.cc
  starboard/win/win32/cobalt/configuration.py
Labels: on_device

#1058 Add force enable command line flag for Telemetry
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client_test.cc
Labels: cp-24.lts.1+

#656 Allow sending of browser logs to devtools.
  cobalt/debug/BUILD.gn
  cobalt/debug/backend/log_agent.cc
  cobalt/debug/backend/log_agent.h
  cobalt/debug/console/command_manager.cc
  cobalt/debug/console/command_manager.h
Labels: on_device

#1077 Remove nb::scoped_ptr
  nb/BUILD.gn
  nb/bidirectional_fit_reuse_allocator_test.cc
  nb/first_fit_reuse_allocator_test.cc
  nb/scoped_ptr.h
Labels: on_device
