Repository youtube/cobalt, pull requests merged in 2024-01, with the labels that each got.

#2190 Set evergreen platform tests to use starboard toolchain
  starboard/BUILD.gn
  starboard/android/shared/BUILD.gn
  starboard/build/config/starboard_target_type.gni
  starboard/elf_loader/BUILD.gn
  starboard/linux/x64x11/shared/platform_configuration/configuration.gni
  starboard/loader_app/BUILD.gn
  starboard/raspi/2/platform_configuration/configuration.gni
  third_party/crashpad/wrapper/BUILD.gn
Labels: on_device

#2202 Enable more passed tests
  base/BUILD.gn
Labels: runtest

#2192 Remove unused core dump handler code
  cobalt/browser/application.cc
  cobalt/browser/browser_module.cc
  cobalt/browser/browser_module.h
  cobalt/dom/node.cc
  cobalt/dom_parser/libxml_parser_wrapper.cc
  cobalt/h5vcc/h5vcc_crash_log.cc
  cobalt/h5vcc/h5vcc_crash_log.h
  cobalt/loader/net_fetcher.cc
  cobalt/script/script_runner.cc
Labels: on_device

#2266 Revert "Revert "Cherry pick PR #1909: Use -std=gnu++17 in mac GN configuration""
  starboard/build/config/mac/BUILD.gn
Labels: on_device

#2044 [android] Handle mediacodec callback with a handler thread
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/audio_decoder.cc
  starboard/android/shared/audio_decoder.h
  starboard/android/shared/audio_renderer_passthrough.cc
  starboard/android/shared/audio_renderer_passthrough.h
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/media_is_video_supported.cc
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/video_decoder.cc
  starboard/android/shared/video_decoder.h
Labels: cp-24.lts.1+, on_device, outside collaborator

#2300 [media] Enable NEON optimization for WSOLA algorithm
  starboard/build/config/BUILD.gn
  starboard/shared/starboard/player/filter/wsola_internal.cc
Labels: cp-24.lts.1+, on_device

#2173 [android] Log the effective size of the AudioTrack buffer
  starboard/android/apk/app/src/main/java/dev/cobalt/media/AudioTrackBridge.java
Labels: cp-24.lts.1+

#1663 [android] Support KEY_MAX_INPUT_SIZE configurable from the webapp
  cobalt/demos/content/configure-max-video-input-size/configure-max-video-input-size.html
  cobalt/demos/content/configure-max-video-input-size/configure-max-video-input-size.js
  cobalt/demos/content/configure-max-video-input-size/dash-audio.mp4
  cobalt/demos/content/configure-max-video-input-size/vp9-720p.webm
  cobalt/dom/html_media_element.cc
  cobalt/dom/html_media_element.h
  cobalt/dom/html_video_element.idl
  cobalt/media/base/pipeline.h
  cobalt/media/base/sbplayer_bridge.cc
  cobalt/media/base/sbplayer_bridge.h
  cobalt/media/base/sbplayer_pipeline.cc
  cobalt/media/base/sbplayer_pipeline.h
  cobalt/media/player/web_media_player.h
  cobalt/media/player/web_media_player_impl.cc
  cobalt/media/sandbox/web_media_player_helper.cc
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/BUILD.gn
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/player_create.cc
  starboard/android/shared/player_set_max_video_input_size.cc
  starboard/android/shared/player_set_max_video_input_size.h
  starboard/android/shared/system_get_extensions.cc
  starboard/android/shared/video_decoder.cc
  starboard/android/shared/video_decoder.h
  starboard/android/shared/video_max_video_input_size.cc
  starboard/android/shared/video_max_video_input_size.h
  starboard/extension/extension_test.cc
  starboard/extension/player_set_max_video_input_size.h
  starboard/shared/starboard/player/filter/filter_based_player_worker_handler.cc
  starboard/shared/starboard/player/filter/filter_based_player_worker_handler.h
  starboard/shared/starboard/player/filter/player_components.cc
  starboard/shared/starboard/player/filter/player_components.h
  starboard/shared/starboard/player/filter/testing/player_components_test.cc
  starboard/shared/starboard/player/filter/testing/video_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/video_decoder_test_fixture.cc
  starboard/shared/starboard/player/player_worker.h
Labels: cp-24.lts.1+, on_device

#2260 Update "Set up your environment - Linux" link
  cobalt/site/docs/development/setup-android.md
Labels: outside collaborator

#2321 [android] cleanup unused includes for setting KEY_MAX_INPUT_SIZE
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/player_components_factory.h
  starboard/extension/player_set_max_video_input_size.h
Labels: cp-24.lts.1+
