Repository youtube/cobalt, pull requests merged in 2024-02, with the labels that each got.

#2262 Introduce pthread_mutex APIs.
  starboard/build/config/modular/BUILD.gn
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/BUILD.gn
  starboard/nplb/posix_compliance/posix_mutex_acquire_test.cc
  starboard/nplb/posix_compliance/posix_mutex_acquire_try_test.cc
  starboard/nplb/posix_compliance/posix_mutex_create_test.cc
  starboard/nplb/posix_compliance/posix_mutex_destroy_test.cc
  starboard/shared/modular/BUILD.gn
  starboard/shared/modular/posix_pthread_wrappers.cc
  starboard/shared/modular/posix_pthread_wrappers.h
  starboard/shared/win32/posix_emu/include/pthread.h
  starboard/shared/win32/posix_emu/pthread.cc
  starboard/stub/platform_configuration/BUILD.gn
  starboard/win/shared/BUILD.gn
  third_party/abseil-cpp/absl/base/internal/sysinfo.cc
  third_party/musl/BUILD.gn
  third_party/musl/include/pthread.h
  third_party/musl/include/sys/types.h
  third_party/musl/src/starboard/pthread/pthread.c
  third_party/musl/src/starboard/pthread/pthread.h
Labels: on_device

#2009 Change base image to Debian 11
  .github/workflows/stub.yaml
  docker/linux/base/Dockerfile
  starboard/tools/api_leak_detector/stub/debug/gn_built_docker_debian11_manifest
  starboard/tools/api_leak_detector/stub/devel/gn_built_docker_debian11_manifest
  starboard/tools/api_leak_detector/stub/gold/gn_built_docker_debian11_manifest
  starboard/tools/api_leak_detector/stub/qa/gn_built_docker_debian11_manifest
Labels: on_device

#2413 Enable POSIX compliance tests for SB14 and SB15.
  starboard/nplb/posix_compliance/posix_arpa_inet_test.cc
  starboard/nplb/posix_compliance/posix_memory_map_test.cc
  starboard/nplb/posix_compliance/posix_mutex_acquire_test.cc
  starboard/nplb/posix_compliance/posix_mutex_acquire_try_test.cc
  starboard/nplb/posix_compliance/posix_mutex_create_test.cc
  starboard/nplb/posix_compliance/posix_mutex_destroy_test.cc
  starboard/nplb/posix_compliance/posix_string_compare_no_case_n_test.cc
  starboard/nplb/posix_compliance/posix_string_compare_no_case_test.cc
  starboard/nplb/posix_compliance/posix_string_format_test.cc
  starboard/nplb/posix_compliance/posix_string_format_wide_test.cc
  starboard/nplb/posix_compliance/posix_time_test.cc
  third_party/musl/src/starboard/pthread/pthread.c
Labels: on_device

#2376 [android] return invalid player if output mode is invalid
  cobalt/media/base/sbplayer_bridge.cc
Labels: on_device

#2387 Remove the option to start crash handler at launch
  starboard/CHANGELOG.md
  starboard/android/shared/BUILD.gn
  starboard/android/shared/android_main.cc
  starboard/doc/crash_handlers.md
  starboard/linux/shared/BUILD.gn
  starboard/linux/x64x11/main.cc
  starboard/raspi/shared/BUILD.gn
  starboard/raspi/shared/main.cc
  starboard/shared/starboard/starboard_switches.cc
  starboard/shared/starboard/starboard_switches.h
  starboard/stub/BUILD.gn
  third_party/crashpad/wrapper/wrapper.cc
  third_party/crashpad/wrapper/wrapper.h
  third_party/crashpad/wrapper/wrapper_stub.cc
Labels: on_device

#2432 Run ODT job directly on a runner.
  .github/workflows/main.yaml
Labels: on_device

#2414 [android] Log AudioFormat and the buffer size for AudioTrack
  starboard/android/apk/app/src/main/java/dev/cobalt/media/AudioTrackBridge.java
Labels: on_device

#2436 Add temporary flags to evergreen config for modular builds
  .github/config/linux-modular.json
  .github/workflows/main.yaml
  cobalt/BUILD.gn
  cobalt/browser/web_module.cc
  cobalt/worker/worker_global_scope.cc
  starboard/build/config/BUILD.gn
  starboard/build/config/BUILDCONFIG.gn
  starboard/evergreen/shared/platform_configuration/BUILD.gn
  starboard/linux/shared/platform_configuration/BUILD.gn
  tools/lz4_compress/lz4_compress.cc
Labels: runtest

#2458 Revert "[android] Handle mediacodec callback with a handler thread (#2044)"
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/audio_decoder.cc
  starboard/android/shared/audio_decoder.h
  starboard/android/shared/audio_renderer_passthrough.cc
  starboard/android/shared/audio_renderer_passthrough.h
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/media_is_video_supported.cc
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/video_decoder.cc
  starboard/android/shared/video_decoder.h
Labels: cp-24.lts.1+
