Repository youtube/cobalt, pull requests merged in 2024-09, with the labels that each got.

#4022 Add validation ai_addrlen in PosixSocketResolveTest
  starboard/nplb/posix_compliance/posix_socket_resolve_test.cc
Labels: on_device

#4107 Remove broken filter from Android
  starboard/android/shared/test_filters.py
Labels: on_device

#4098 Cleanup for SB_API_VERSION < 17 checks
  cobalt/media/base/sbplayer_bridge.h
  cobalt/media/base/sbplayer_pipeline.cc
  cobalt/media/base/sbplayer_pipeline.h
  cobalt/media/media_module.cc
  cobalt/media/media_module.h
  cobalt/media/player/web_media_player_impl.cc
  cobalt/media/player/web_media_player_impl.h
  media/base/starboard_utils.cc
  starboard/raspi/shared/application_dispmanx.h
  starboard/raspi/shared/configuration_constants.cc
  starboard/raspi/shared/main.cc
  starboard/raspi/shared/run_starboard_main.cc
  starboard/raspi/shared/system_get_property.cc
  starboard/shared/enhanced_audio/enhanced_audio.cc
  starboard/shared/enhanced_audio/enhanced_audio_player_write_samples.cc
  starboard/shared/enhanced_audio/enhanced_audio_player_write_samples.h
  starboard/shared/enhanced_audio/player_write_samples_checked.cc
  starboard/shared/modular/cobalt_layer_posix_directory_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_errno_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_mmap_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_pthread_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_stat_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_time_abi_wrappers.cc
  starboard/shared/modular/cobalt_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/starboard/application.cc
  starboard/shared/starboard/application.h
  starboard/shared/starboard/log_raw_format.cc
  starboard/shared/starboard/media/codec_util.cc
  starboard/shared/starboard/media/media_get_audio_configuration.cc
  starboard/shared/starboard/media/media_get_buffer_alignment.cc
  starboard/shared/starboard/media/media_util.cc
  starboard/shared/starboard/media/media_util.h
  starboard/shared/starboard/media/media_util_test.cc
  starboard/shared/starboard/media/mime_util.cc
  starboard/shared/starboard/player/filter/filter_based_player_worker_handler.cc
  starboard/shared/starboard/player/filter/stub_audio_decoder.cc
  starboard/shared/starboard/player/filter/testing/test_util.cc
  starboard/shared/starboard/player/player_create.cc
  starboard/shared/starboard/player/player_get_audio_configuration.cc
  starboard/shared/starboard/player/player_get_info.cc
  starboard/shared/starboard/player/player_get_preferred_output_mode_prefer_punchout.cc
  starboard/shared/starboard/player/player_internal.cc
  starboard/shared/starboard/player/player_internal.h
  starboard/shared/starboard/player/player_seek.cc
  starboard/shared/starboard/player/player_write_samples.cc
  starboard/shared/starboard/player/video_dmp_reader.cc
  starboard/shared/starboard/queue_application.h
  starboard/shared/stub/player_get_audio_configuration.cc
  starboard/shared/stub/player_get_info.cc
  starboard/shared/stub/player_seek.cc
  starboard/shared/stub/player_write_samples.cc
  starboard/shared/stub/socket_waiter_add.cc
  starboard/shared/stub/socket_waiter_remove.cc
  starboard/shared/x11/application_x11.cc
  starboard/shared/x11/application_x11.h
Labels: on_device

#4109 Remove SB_HAS_IPV6 config
  cobalt/csp/source_list_test.cc
  cobalt/network/local_network_test.cc
  cobalt/site/docs/reference/starboard/configuration-public.md
  net/socket/tcp_socket_unittest.cc
  starboard/android/shared/configuration_public.h
  starboard/evergreen/arm/hardfp/configuration_public.h
  starboard/evergreen/arm/softfp/configuration_public.h
  starboard/evergreen/arm64/configuration_public.h
  starboard/evergreen/x64/configuration_public.h
  starboard/linux/shared/configuration_public.h
  starboard/nplb/posix_compliance/posix_socket_accept_test.cc
  starboard/nplb/posix_compliance/posix_socket_bind_test.cc
  starboard/nplb/posix_compliance/posix_socket_errno_test.cc
  starboard/nplb/posix_compliance/posix_socket_helpers.cc
  starboard/nplb/posix_compliance/posix_socket_helpers.h
  starboard/nplb/posix_compliance/posix_socket_listen_test.cc
  starboard/nplb/posix_compliance/posix_socket_set_options_test.cc
  starboard/nplb/socket_accept_test.cc
  starboard/nplb/socket_bind_test.cc
  starboard/nplb/socket_connect_test.cc
  starboard/nplb/socket_create_test.cc
  starboard/nplb/socket_get_interface_address_test.cc
  starboard/nplb/socket_get_local_address_test.cc
  starboard/nplb/socket_is_connected_and_idle_test.cc
  starboard/nplb/socket_is_connected_test.cc
  starboard/nplb/socket_listen_test.cc
  starboard/nplb/socket_receive_from_test.cc
  starboard/nplb/socket_resolve_test.cc
  starboard/nplb/socket_send_to_test.cc
  starboard/nplb/socket_set_options_test.cc
  starboard/nplb/socket_waiter_add_test.cc
  starboard/nplb/socket_waiter_remove_test.cc
  starboard/nplb/socket_waiter_wait_test.cc
  starboard/nplb/socket_waiter_wait_timed_test.cc
  starboard/nplb/socket_wrapper_test.cc
  starboard/raspi/shared/configuration_public.h
  starboard/shared/linux/socket_get_interface_address.cc
  starboard/shared/posix/socket_bind.cc
  starboard/shared/posix/socket_internal.cc
  starboard/shared/posix/socket_is_ipv6_supported.cc
  starboard/stub/configuration_public.h
Labels: on_device

#4113 Remove instance of SbFileAtomicReplace
  components/update_client/cobalt_slot_management_test.cc
Labels: on_device

#4122 Remove unused config variables
  cobalt/renderer/rasterizer/skia/skia/config/SkUserConfig.h
  cobalt/site/docs/reference/starboard/modules/configuration_constants.md
  starboard/android/shared/configuration_constants.cc
  starboard/configuration_constants.h
  starboard/elf_loader/exported_symbols.cc
  starboard/linux/shared/configuration_constants.cc
  starboard/raspi/shared/configuration_constants.cc
  starboard/stub/configuration_constants.cc
  third_party/icu/source/common/unicode/putil.h
Labels: on_device

#4120 Delete cwrappers
  base/BUILD.gn
  cobalt/build/cobalt_configuration.py
  cobalt/css_parser/scanner.cc
  cobalt/debug/BUILD.gn
  cobalt/h5vcc/BUILD.gn
  cobalt/media/BUILD.gn
  cobalt/media/sandbox/BUILD.gn
  media/BUILD.gn
  starboard/BUILD.gn
  starboard/build/config/starboard_target_type.gni
  starboard/build/platform_configuration.py
  starboard/client_porting/cwrappers/BUILD.gn
  starboard/client_porting/cwrappers/pow_wrapper.cc
  starboard/client_porting/cwrappers/pow_wrapper.h
  starboard/client_porting/cwrappers/pow_wrapper_test.cc
  starboard/client_porting/eztime/BUILD.gn
  starboard/contrib/cast/cast_starboard_api/samples/BUILD.gn
  starboard/examples/glclear/BUILD.gn
  starboard/examples/window/BUILD.gn
  starboard/extension/cwrappers.h
  starboard/extension/extension_test.cc
  starboard/loader_app/BUILD.gn
  third_party/QR-Code-generator/BUILD.gn
  third_party/abseil-cpp/absl/time/internal/cctz/BUILD.gn
  third_party/googletest/BUILD.gn
  third_party/icu/BUILD.gn
  third_party/icu/source/i18n/plurrule.cpp
  third_party/libwebp/src/enc/picture_csp_enc.c
  third_party/libwebp/src/enc/quant_enc.c
  third_party/libxml/src/xpath.c
Labels: on_device

#4125 Remove starboard dep on cobalt/build/contents_dir.gni
  third_party/icu/BUILD.gn
Labels: runtest

#4137 [XB1] Expand hardware video decoder logs
  starboard/shared/win32/media_transform.cc
  starboard/shared/win32/media_transform.h
  starboard/shared/win32/video_decoder.cc
  starboard/shared/win32/video_decoder.h
Labels: cp-25.lts.1+

#4112 [android] Fix incorrect JNI call on MediaCodecBridge
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.cc
Labels: on_device

#4102 Add nplb compiler check for all linux based platforms
  starboard/nplb/BUILD.gn
  starboard/nplb/compiler_compliance/cpp_compiler_version_check.cc
Labels: runtest

#4127 Download test artifacts
  .github/actions/on_device_tests/action.yaml
  .github/actions/on_host_test/action.yaml
  tools/on_device_tests_gateway.proto
  tools/on_device_tests_gateway_client.py
Labels: on_device, cp-25.lts.1+

#4121 Add socket watcher closure if no pending operations
  net/socket/tcp_socket_starboard.cc
Labels: on_device

#4134 Clean up sockets for SB17
  base/message_loop/message_pump_io_starboard.cc
  base/message_loop/message_pump_io_starboard.h
  base/message_loop/message_pump_io_starboard_unittest.cc
  base/task/current_thread.cc
  base/task/current_thread.h
  net/BUILD.gn
  net/base/address_family.cc
  net/base/address_family.h
  net/base/features.cc
  net/base/features.h
  net/base/net_errors_posix.cc
  net/base/net_errors_starboard.cc
  net/socket/socket_descriptor.cc
  net/socket/socket_descriptor.h
  net/socket/socket_options.cc
  net/socket/socket_posix.cc
  net/socket/socket_posix.h
  net/socket/tcp_socket.h
  net/socket/tcp_socket_posix.cc
  net/socket/tcp_socket_posix.h
  net/socket/tcp_socket_starboard.cc
  net/socket/tcp_socket_starboard.h
  net/socket/udp_socket.h
  net/socket/udp_socket_posix.cc
  net/socket/udp_socket_posix.h
  net/socket/udp_socket_starboard.cc
  net/socket/udp_socket_starboard.h
Labels: on_device

#4162 Create 25.LTS.10.md
  cobalt/site/docs/releases/25.LTS.10.md
Labels: outside collaborator

#4129 remove MSC_VER from starboard
  starboard/common/optional.h
  starboard/configuration.h
  starboard/elf_loader/exported_symbols.cc
  starboard/shared/modular/starboard_layer_posix_stat_abi_wrappers.cc
  starboard/shared/testing/no_inline.h
  starboard/types.h
Labels: on_device

#4158 Clean up socket.h header
  starboard/android/shared/BUILD.gn
  starboard/common/socket.cc
  starboard/common/socket.h
  starboard/elf_loader/exported_symbols.cc
  starboard/linux/shared/BUILD.gn
  starboard/nplb/BUILD.gn
  starboard/nplb/socket_accept_test.cc
  starboard/nplb/socket_bind_test.cc
  starboard/nplb/socket_connect_test.cc
  starboard/nplb/socket_create_test.cc
  starboard/nplb/socket_get_interface_address_test.cc
  starboard/nplb/socket_get_local_address_test.cc
  starboard/nplb/socket_helpers.cc
  starboard/nplb/socket_helpers.h
  starboard/nplb/socket_is_connected_and_idle_test.cc
  starboard/nplb/socket_is_connected_test.cc
  starboard/nplb/socket_join_multicast_group_test.cc
  starboard/nplb/socket_listen_test.cc
  starboard/nplb/socket_receive_from_test.cc
  starboard/nplb/socket_resolve_test.cc
  starboard/nplb/socket_send_to_test.cc
  starboard/nplb/socket_set_options_test.cc
  starboard/nplb/socket_waiter_add_test.cc
  starboard/nplb/socket_waiter_remove_test.cc
  starboard/nplb/socket_waiter_wait_test.cc
  starboard/nplb/socket_waiter_wait_timed_test.cc
  starboard/nplb/socket_wrapper_test.cc
  starboard/raspi/shared/BUILD.gn
  starboard/shared/libevent/socket_waiter_internal.cc
  starboard/shared/posix/socket_free_resolution.cc
  starboard/shared/posix/socket_is_connected.cc
  starboard/shared/posix/socket_is_connected_and_idle.cc
  starboard/shared/posix/socket_join_multicast_group.cc
  starboard/shared/posix/socket_resolve.cc
  starboard/shared/posix/socket_set_broadcast.cc
  starboard/shared/posix/socket_set_receive_buffer_size.cc
  starboard/shared/posix/socket_set_send_buffer_size.cc
  starboard/shared/posix/socket_set_tcp_keep_alive.cc
  starboard/shared/posix/socket_set_tcp_no_delay.cc
  starboard/shared/posix/socket_set_tcp_window_scaling.cc
  starboard/shared/starboard/net_args.cc
  starboard/shared/starboard/net_args.h
  starboard/shared/stub/socket_free_resolution.cc
  starboard/shared/stub/socket_is_connected.cc
  starboard/shared/stub/socket_is_connected_and_idle.cc
  starboard/shared/stub/socket_join_multicast_group.cc
  starboard/shared/stub/socket_resolve.cc
  starboard/shared/stub/socket_set_broadcast.cc
  starboard/shared/stub/socket_set_receive_buffer_size.cc
  starboard/shared/stub/socket_set_send_buffer_size.cc
  starboard/shared/stub/socket_set_tcp_keep_alive.cc
  starboard/shared/stub/socket_set_tcp_no_delay.cc
  starboard/shared/stub/socket_set_tcp_window_scaling.cc
  starboard/socket.h
  starboard/stub/BUILD.gn
Labels: on_device

#4156 Polish test result upload
  .github/actions/on_device_tests/action.yaml
  .github/actions/on_host_test/action.yaml
Labels: on_device
