Repository youtube/cobalt, pull requests merged in 2024-07, with the labels that each got.

#3721 Translate the errno values to musl errno values.
  starboard/elf_loader/exported_symbols.cc
  starboard/shared/modular/BUILD.gn
  starboard/shared/modular/cobalt_layer_posix_errno_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_errno_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_errno_abi_wrappers.h
  third_party/musl/include/errno.h
Labels: on_device

#3752 Default quic to on for all platforms
  cobalt/network/url_request_context.cc
  starboard/android/shared/configuration.cc
Labels: cp-25.lts.1+

#3763 Use toolchain defined in starboard path
  starboard/loader_app/BUILD.gn
Labels: outside collaborator

#3426 Fix linux crashpad 64bit native build
  third_party/boringssl/BUILD.gn
Labels: outside collaborator

#3797 Clean up ICU initialization
  starboard/client_porting/icu_init/icu_init.cc
  starboard/client_porting/icu_init/icu_init.h
  third_party/icu/source/common/udata.cpp
Labels: on_device

#3812 Remove SB impls of uprv_mapFile/uprv_unmapFile
  third_party/icu/source/common/umapfile.cpp
  third_party/icu/source/common/umapfile.h
Labels: on_device

#3388 Build and filter more net unittests
  cobalt/build/cobalt_configuration.py
  net/BUILD.gn
  net/disk_cache/cache_util_unittest.cc
  net/third_party/quiche/BUILD.gn
  third_party/boringssl/src/ssl/ssl_session.cc
  url/gurl_unittest.cc
Labels: on_device, cp-25.lts.1+

#3823 Add field for fixed android appStart time
  cobalt/dom/performance_lifecycle_timing.cc
  cobalt/dom/performance_lifecycle_timing.h
  cobalt/dom/performance_lifecycle_timing.idl
  starboard/android/apk/app/src/main/java/dev/cobalt/coat/StarboardBridge.java
  starboard/android/shared/BUILD.gn
  starboard/android/shared/application_android.cc
  starboard/android/shared/application_android.h
  starboard/android/shared/system_get_extensions.cc
  starboard/android/shared/system_info_api.cc
  starboard/android/shared/system_info_api.h
  starboard/extension/extension_test.cc
  starboard/extension/system_info.h
Labels: cp-25.lts.1+

#3817 Finish cleaning up directory references
  starboard/android/shared/android_main.cc
  starboard/common/file.cc
  starboard/shared/win32/posix_emu/dirent.cc
Labels: on_device

#3840 Clean up more directory references
  base/files/file_enumerator_starboard.cc
  starboard/shared/win32/posix_emu/dirent.cc
  starboard/win/win32/test_filters.py
Labels: on_device, cp-25.lts.1+

#3882 Deprecate SbDirectory APIs
  starboard/android/shared/directory_close.cc
  starboard/android/shared/directory_get_next.cc
  starboard/android/shared/directory_open.cc
  starboard/directory.h
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/directory_close_test.cc
  starboard/nplb/posix_compliance/posix_directory_get_next_test.cc
  starboard/nplb/system_sign_with_certification_secret_key_test.cc
  starboard/shared/iso/directory_close.cc
  starboard/shared/iso/directory_get_next.cc
  starboard/shared/iso/directory_open.cc
  starboard/shared/iso/impl/directory_close.h
  starboard/shared/iso/impl/directory_get_next.h
  starboard/shared/iso/impl/directory_open.h
  starboard/shared/stub/directory_close.cc
  starboard/shared/stub/directory_get_next.cc
  starboard/shared/stub/directory_open.cc
  starboard/shared/win32/directory_close.cc
  starboard/shared/win32/directory_get_next.cc
  starboard/shared/win32/directory_open.cc
Labels: on_device

#3864 Switch starboard/common RefCounted to standard atomics
  starboard/common/ref_counted.cc
  starboard/common/ref_counted.h
Labels: on_device

#3892 Remove directory reference from Android
  starboard/android/shared/file_can_open.cc
Labels: on_device

#3879 Replace starboard::RWLock with std::shared_mutex
  starboard/common/BUILD.gn
  starboard/common/rwlock.cc
  starboard/common/rwlock.h
  starboard/nplb/BUILD.gn
  starboard/nplb/rwlock_test.cc
  third_party/llvm-project/libunwind/src/RWMutex.hpp
  v8/src/base/platform/mutex.cc
  v8/src/base/platform/mutex.h
Labels: on_device

#3906 Fix stub ReplaceFile implementation
  base/files/file_util_starboard.cc
Labels: cp-25.lts.1+

#3884 Update trunk to Starboard 17
  starboard/build/config/base_configuration.gni
  starboard/configuration.h
  starboard/linux/x64x11/system_get_property_impl.cc
  starboard/nplb/nplb_evergreen_compat_tests/sabi_test.cc
  starboard/sabi/arm/hardfp/sabi-v17.json
  starboard/sabi/arm/softfp/sabi-v17.json
  starboard/sabi/arm64/sabi-v17.json
  starboard/sabi/schema/sabi-v17.schema.json
  starboard/sabi/x64/sysv/sabi-v17.json
  starboard/sabi/x64/windows/sabi-v17.json
  starboard/sabi/x86/sabi-v17.json
Labels: on_device
