Repository youtube/cobalt, pull requests merged in 2024-06, with the labels that each got.

#3415 [media] Deprecate SbMediaGetBufferStorageType()
  starboard/CHANGELOG.md
  starboard/elf_loader/exported_symbols.cc
  starboard/media.h
  starboard/nplb/media_buffer_test.cc
  starboard/shared/starboard/media/media_get_buffer_storage_type.cc
  starboard/shared/stub/media_get_buffer_storage_type.cc
Labels: runtest, cp-25.lts.1+

#3442 Fix pids in base tracing reports
  base/process/process_starboard.cc
  starboard/common/BUILD.gn
  starboard/common/process.cc
  starboard/common/process.h
  v8/src/base/platform/platform-starboard.cc
Labels: cp-25.lts.1+

#3452 Add defensive checks around Lottie animation loading
  cobalt/renderer/rasterizer/skia/skottie_animation.cc
Labels: on_device

#3450 Stop updater_test from deleting its own binary
  chrome/updater/utils_test.cc
Labels: on_device

#3441 Internal docker cleanup
  docker-compose-windows-internal.yml
Labels: cp-25.lts.1+

#3466 Re-enable SbThreadGetIdTest
  starboard/nplb/thread_get_id_test.cc
Labels: on_device

#3474 Restore SbThreadGetId()
  cobalt/base/log_message_handler.cc
  cobalt/dom/serialized_algorithm_runner.h
  cobalt/loader/fetcher_cache.cc
  cobalt/loader/fetcher_cache.h
  starboard/common/log.cc
  starboard/common/recursive_mutex.cc
  starboard/common/recursive_mutex.h
  starboard/common/thread_collision_warner.cc
  starboard/shared/starboard/player/job_queue.cc
  starboard/shared/starboard/player/job_queue.h
  starboard/shared/starboard/thread_checker.h
  third_party/abseil-cpp/absl/base/internal/sysinfo_starboard.cc
  third_party/skia/src/core/SkThreadID.cpp
  v8/src/base/platform/platform-starboard.cc
Labels: on_device

#3461 Work around URL encoding in raw Lottie data
  cobalt/dom/lottie_player.cc
  cobalt/layout_tests/testdata/BUILD.gn
  cobalt/layout_tests/testdata/lottie-player/layout_tests.txt
  cobalt/layout_tests/testdata/lottie-player/lottie-data-urls-expected.png
  cobalt/layout_tests/testdata/lottie-player/lottie-data-urls.html
Labels: on_device

#3484 Bump Starboard version in site gen script
  cobalt/site/scripts/cobalt_module_reference.py
Labels: runtest, cp-25.lts.1+

#3487 Fix hanging nplb tests on win32
  starboard/shared/win32/posix_emu/pthread.cc
Labels: on_device

#3488 [android] Create MediaFormatBuilder.java
  starboard/android/apk/apk_sources.gni
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaFormatBuilder.java
Labels: runtest

#3502 Disable GLES sampler objects in Skia
  third_party/skia/src/gpu/gl/GrGLCaps.cpp
Labels: on_device

#3513 [media] Refactor audio write ahead
  cobalt/media/base/sbplayer_pipeline.cc
Labels: cp-25.lts.1+

#3271 [media] Limit max number of buffers to write with audio write ahead
  cobalt/media/base/sbplayer_pipeline.cc
  cobalt/media/base/sbplayer_pipeline.h
Labels: on_device

#3204 Update Cobalt versioning scheme
  cobalt/doc/branching.md
  cobalt/doc/versioning.md
  cobalt/version.h
Labels: outside collaborator

#3325 [android] Support configuring maximum number of samples per write to SbPlayer from webapp
  cobalt/media/base/sbplayer_pipeline.cc
  cobalt/media/base/sbplayer_pipeline.h
  cobalt/media/media_module.cc
  cobalt/media/media_module.h
  cobalt/media/player/web_media_player_impl.cc
  cobalt/media/player/web_media_player_impl.h
  starboard/android/shared/BUILD.gn
  starboard/android/shared/player_get_maximum_number_of_samples_per_write.cc
Labels: on_device

#3550 [android] Switch from scoped_ptr to std::unique_ptr
  starboard/android/shared/application_android.h
  starboard/android/shared/audio_decoder.h
  starboard/android/shared/audio_renderer_passthrough.cc
  starboard/android/shared/configuration_public.h
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_decoder.h
  starboard/android/shared/microphone_impl.cc
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/player_create.cc
  starboard/android/shared/video_decoder.cc
  starboard/android/shared/video_decoder.h
Labels: on_device

#3546 Transfer HardwareBackendImage ownership at destruction
  cobalt/renderer/rasterizer/skia/hardware_image.cc
Labels: runtest, on_device, cp-25.lts.1+

#3564 [android] Disable failing WriteSingleBatch tests
  starboard/android/shared/test_filters.py
Labels: on_device

#3468 [nplb] Add SbPlayerGetMediaTimeTests for checking media time after seek/reset
  starboard/android/x86/test_filters.py
  starboard/evergreen/x64/test_filters.py
  starboard/nplb/BUILD.gn
  starboard/nplb/player_get_media_time_test.cc
  starboard/raspi/shared/test_filters.py
  starboard/shared/starboard/player/filter/adaptive_audio_decoder_internal.cc
  starboard/win/win32/test_filters.py
Labels: on_device

#3584 [android] Fix failing WriteSingleBatch tests
  starboard/android/shared/test_filters.py
  starboard/nplb/player_write_sample_test.cc
Labels: on_device

#3599 Revert "Deprecate SbDirectoryOpen and SbDirectoryClose APIs"
  base/files/file_enumerator_starboard.cc
  cobalt/media/sandbox/fuzzer_app.cc
  net/cert/internal/trust_store_in_memory_starboard.cc
  starboard/android/shared/BUILD.gn
  starboard/android/shared/platform_configuration/BUILD.gn
  starboard/android/shared/posix_emu/dirent.cc
  starboard/android/shared/posix_emu/stat.cc
  starboard/elf_loader/exported_symbols.cc
  starboard/loader_app/app_key_files.cc
  starboard/loader_app/drain_file.cc
  starboard/loader_app/installation_manager_test.cc
  starboard/nplb/BUILD.gn
  starboard/nplb/directory_get_next_test.cc
  starboard/nplb/directory_open_test.cc
  starboard/nplb/posix_compliance/posix_directory_get_next_test.cc
  starboard/nplb/posix_compliance/posix_directory_open_test.cc
  starboard/nplb/system_get_path_test.cc
  starboard/shared/linux/dev_input/dev_input.cc
  starboard/shared/win32/posix_emu/dirent.cc
  starboard/shared/win32/posix_emu/include/dirent.h
  starboard/tools/api_leak_detector/api_leak_detector.py
  starboard/win/shared/BUILD.gn
  third_party/musl/BUILD.gn
  third_party/musl/src/starboard/dirent.c
Labels: on_device

#3600 Fix MediaCodec videoInputSize
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
Labels: on_device

#3243 Clean up SbFile usages
  base/files/file.h
  base/files/file_enumerator.h
  base/files/file_enumerator_starboard.cc
  base/files/file_enumerator_unittest.cc
  base/files/file_starboard.cc
  base/files/file_unittest.cc
  base/files/file_util_starboard.cc
  base/files/file_util_unittest.cc
  base/files/platform_file.h
  base/files/scoped_file.cc
  base/files/scoped_file.h
  base/logging.cc
  cobalt/base/tokens.h
  cobalt/media/sandbox/format_guesstimator.cc
  cobalt/media/sandbox/web_media_player_sandbox.cc
  cobalt/renderer/rasterizer/skia/skia/src/ports/SkOSFile_cobalt.cc
  cobalt/renderer/test/png_utils/png_decode.cc
  cobalt/renderer/test/png_utils/png_encode.cc
  cobalt/speech/microphone_fake.cc
  cobalt/trace_event/json_file_outputter.cc
  cobalt/watchdog/watchdog.cc
  cobalt/websocket/web_socket.h
  net/proxy_resolution/proxy_config_service_linux.cc
  starboard/common/file.h
  starboard/loader_app/app_key_files.cc
  starboard/loader_app/drain_file_helper.cc
  starboard/loader_app/drain_file_test.cc
  starboard/loader_app/installation_manager_test.cc
  starboard/loader_app/reset_evergreen_update_test.cc
  starboard/nplb/nplb_evergreen_compat_tests/storage_test.cc
  starboard/nplb/posix_compliance/posix_socket_send_test.cc
  starboard/nplb/posix_compliance/posix_socket_sendto_test.cc
  starboard/nplb/system_get_path_test.cc
  starboard/shared/linux/system_get_used_cpu_memory.cc
  starboard/shared/starboard/link_receiver.cc
  starboard/shared/starboard/localized_strings.cc
  starboard/shared/starboard/player/file_cache_reader.cc
  starboard/shared/starboard/player/filter/testing/file_cache_reader_test.cc
  starboard/shared/uwp/log_writer_win32.cc
  starboard/shared/widevine/widevine_storage.cc
  starboard/shared/win32/posix_emu/include/fcntl.h
  starboard/shared/win32/posix_emu/include/unistd.h
  starboard/shared/win32/posix_emu/socket.cc
  starboard/tools/api_leak_detector/api_leak_detector.py
  starboard/win/win32/test_filters.py
  third_party/googletest/src/googletest/src/gtest.cc
  third_party/musl/src/starboard/sys/stat.c
Labels: on_device

#3613 Fix the pthread_cond_timedwait translation to musl ABI.
  starboard/shared/modular/starboard_layer_posix_errno_abi_wrappers.h
  starboard/shared/modular/starboard_layer_posix_pthread_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_time_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_time_abi_wrappers.h
Labels: on_device

#3611 Add Posix based SocketWaiter APIs for SB16
  starboard/CHANGELOG.md
  starboard/socket_waiter.h
Labels: on_device

#3626 Fix Android layout test failure.
  base/files/file_starboard.cc
Labels: on_device

#3627 [android] Log exception for MediaCodec creation
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
Labels: runtest, cp-25.lts.1+

#3640 Fix ABI wrapping for readdir()
  starboard/shared/modular/BUILD.gn
  starboard/shared/modular/cobalt_layer_posix_directory_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_directory_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_directory_abi_wrappers.h
Labels: on_device

#3641 Fix Raspi largefile test
  base/files/file_starboard.cc
  starboard/raspi/shared/test_filters.py
  third_party/musl/src/starboard/network/socket.c
Labels: on_device

#3597 Always null-check MediaCodec with synchronized Holder
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/apk/app/src/main/java/dev/cobalt/util/SynchronizedHolder.java
Labels: on_device

#3638 [android] Refine MediaCodec error message
  starboard/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
Labels: runtest, cp-25.lts.1+

#3663 [nplb] Disable failing SbPlayerGetMediaTimeTests
  starboard/android/shared/test_filters.py
  starboard/win/win32/test_filters.py
Labels: on_device

#3680 [raspi] Switch from scoped_ptr to std::unique_ptr
  starboard/raspi/shared/application_dispmanx.h
  starboard/raspi/shared/configuration_public.h
  starboard/raspi/shared/dispmanx_util.cc
  starboard/raspi/shared/dispmanx_util.h
  starboard/raspi/shared/player_components_factory.cc
  starboard/raspi/shared/window_internal.h
Labels: on_device

#3696 Add some temporary debugging logs
  cobalt/media/decoder_buffer_allocator.cc
Labels: cp-25.lts.1+

#3681 Deprecate SbFileGetPathInfo
  base/files/file_util_starboard.cc
  starboard/android/shared/file_get_path_info.cc
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/file_get_path_info_test.cc
  starboard/nplb/posix_compliance/posix_directory_get_next_test.cc
  starboard/nplb/system_get_path_test.cc
  starboard/shared/posix/file_get_path_info.cc
  starboard/shared/stub/file_get_path_info.cc
  starboard/shared/win32/file_get_path_info.cc
  third_party/googletest/src/googletest/include/gtest/internal/gtest-port.h
Labels: on_device

#3697 [media] Always enforce memory pool for MSE buffers
  cobalt/media/decoder_buffer_allocator.cc
  cobalt/media/decoder_buffer_allocator.h
  starboard/CHANGELOG.md
  starboard/media.h
  starboard/nplb/media_buffer_test.cc
Labels: on_device

#3704 [media] Re-deprecate SbMediaGetBufferAlignment()
  starboard/CHANGELOG.md
  starboard/elf_loader/exported_symbols.cc
  starboard/media.h
  starboard/nplb/media_buffer_test.cc
  starboard/shared/starboard/media/media_get_buffer_alignment.cc
  starboard/shared/stub/media_get_buffer_alignment.cc
Labels: cp-25.lts.1+
