Repository youtube/cobalt, pull requests merged in 2024-05, with the labels that each got.

#3123 enable errno tests for posix socket rev and send
  starboard/nplb/posix_compliance/posix_socket_receive_test.cc
  starboard/nplb/posix_compliance/posix_socket_recvfrom_test.cc
  starboard/nplb/posix_compliance/posix_socket_send_test.cc
  starboard/nplb/posix_compliance/posix_socket_sendto_test.cc
Labels: on_device

#3138 print errno name
  starboard/nplb/posix_compliance/posix_socket_send_test.cc
  starboard/nplb/posix_compliance/posix_socket_sendto_test.cc
  starboard/shared/win32/posix_emu/socket.cc
Labels: on_device

#3061 [android] Fix VideoDecoderTest.MultipleInputs failures on av1 format
  starboard/shared/starboard/player/filter/testing/video_decoder_test.cc
Labels: on_device

#3157 Migrate trivial pthread_mutex calls
  cobalt/renderer/rasterizer/skia/skia/src/ports/SkMutex_starboard.h
  glimp/egl/scoped_egl_lock.cc
  glimp/egl/scoped_egl_lock.h
  starboard/android/shared/android_media_session_client.cc
  starboard/elf_loader/elf_loader_sandbox.cc
  starboard/shared/ffmpeg/ffmpeg_dispatch.cc
  starboard/shared/ffmpeg/ffmpeg_dynamic_load_dispatch_impl.cc
  starboard/shared/uwp/xb1_media_session_client.cc
  starboard/shared/win32/log_file_impl.cc
  third_party/abseil-cpp/absl/synchronization/mutex_starboard.cc
  third_party/googletest/src/googletest/include/gtest/internal/gtest-port.h
  third_party/protobuf/src/google/protobuf/stubs/common.cc
Labels: on_device

#3161 Remove unused TLSKeyManager
  starboard/shared/starboard/thread_create_local_key.cc
  starboard/shared/starboard/thread_destroy_local_key.cc
  starboard/shared/starboard/thread_get_local_value.cc
  starboard/shared/starboard/thread_local_storage_internal.h
  starboard/shared/starboard/thread_set_local_value.cc
Labels: cp-25.lts.1+

#3090 [android] Filter SbPlayerWriteSampleTest.PartialAudio on audio passthrough
  starboard/nplb/player_test_util.cc
  starboard/nplb/player_test_util.h
  starboard/nplb/player_write_sample_test.cc
Labels: on_device

#3160 Migrate default stack/priority pthread_create calls
  cobalt/watchdog/watchdog.cc
  cobalt/watchdog/watchdog.h
  starboard/android/shared/android_main.cc
  starboard/shared/starboard/link_receiver.cc
  starboard/shared/starboard/player/filter/punchout_video_renderer_sink.cc
  starboard/shared/starboard/player/filter/punchout_video_renderer_sink.h
  starboard/shared/widevine/widevine_timer.cc
  starboard/shared/widevine/widevine_timer.h
  starboard/testing/fake_graphics_context_provider.cc
  starboard/testing/fake_graphics_context_provider.h
  third_party/llvm-project/libcxx/include/__external_threading
  third_party/skia/src/core/SkExecutor.cpp
Labels: on_device

#3176 Fix JNI cleanup on ATV for posix threads.
  starboard/android/shared/jni_env_ext.cc
Labels: on_device

#3151 Add Android asset manager.
  starboard/android/shared/BUILD.gn
  starboard/android/shared/asset_manager.cc
  starboard/android/shared/asset_manager.h
  starboard/android/shared/platform_configuration/BUILD.gn
  starboard/android/shared/posix_emu/file.cc
  starboard/android/shared/test_filters.py
Labels: on_device

#3188 Add ltsnightlyqa channel.
  cobalt/updater/configurator.cc
Labels: runtest, cp-24.lts.1+, cp-25.lts.1+

#3139 Add tests for POSIX file flush, truncate, and delete.
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/BUILD.gn
  starboard/nplb/posix_compliance/posix_file_delete_test.cc
  starboard/nplb/posix_compliance/posix_file_fsync_test.cc
  starboard/nplb/posix_compliance/posix_file_ftruncate_test.cc
  starboard/nplb/posix_compliance/posix_file_read_test.cc
  starboard/shared/modular/BUILD.gn
  starboard/shared/modular/cobalt_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_unistd_abi_wrappers.h
  starboard/shared/win32/posix_emu/include/unistd.h
  starboard/shared/win32/posix_emu/socket.cc
  starboard/tools/api_leak_detector/api_leak_detector.py
  third_party/musl/src/starboard/network/socket.c
  third_party/musl/src/starboard/unistd/unistd.c
Labels: runtest, on_device, cp-25.lts.1+

#3187 Add tests for POSIX write.
  starboard/common/file.cc
  starboard/common/file.h
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/BUILD.gn
  starboard/nplb/posix_compliance/posix_file_open_test.cc
  starboard/nplb/posix_compliance/posix_file_write_test.cc
  starboard/shared/modular/cobalt_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_unistd_abi_wrappers.cc
  starboard/shared/modular/starboard_layer_posix_unistd_abi_wrappers.h
  starboard/shared/win32/posix_emu/include/unistd.h
  starboard/shared/win32/posix_emu/socket.cc
  starboard/tools/api_leak_detector/api_leak_detector.py
  third_party/musl/src/starboard/network/socket.c
Labels: runtest, on_device, cp-25.lts.1+

#3174 Migrate starboard impl code to use pthread_create
  starboard/raspi/shared/open_max/video_decoder.cc
  starboard/raspi/shared/open_max/video_decoder.h
  starboard/shared/alsa/alsa_audio_sink_type.cc
  starboard/shared/ffmpeg/ffmpeg_video_decoder_impl.cc
  starboard/shared/ffmpeg/ffmpeg_video_decoder_impl.h
  starboard/shared/linux/system_network_status.cc
  starboard/shared/linux/system_network_status.h
  starboard/shared/pulse/pulse_audio_sink_type.cc
  starboard/shared/starboard/audio_sink/stub_audio_sink_type.cc
  starboard/shared/starboard/player/job_thread.cc
  starboard/shared/starboard/player/job_thread.h
  starboard/shared/starboard/player/player_worker.cc
  starboard/shared/starboard/player/player_worker.h
  starboard/shared/win32/video_decoder.cc
  starboard/shared/win32/video_decoder.h
Labels: on_device

#3234 Migrate nplb tests to use pthread
  starboard/nplb/atomic_base_test.cc
  starboard/nplb/atomic_test.cc
  starboard/nplb/multiple_player_test.cc
  starboard/nplb/player_write_sample_test.cc
  starboard/nplb/posix_compliance/posix_mutex_acquire_try_test.cc
  starboard/nplb/posix_compliance/posix_thread_get_name_test.cc
  starboard/nplb/posix_compliance/posix_thread_set_name_test.cc
  starboard/nplb/recursive_mutex_test.cc
  starboard/nplb/rwlock_test.cc
  starboard/nplb/semaphore_test.cc
  starboard/nplb/socket_send_to_test.cc
  starboard/nplb/socket_waiter_wait_test.cc
  starboard/nplb/socket_waiter_wake_up_test.cc
  starboard/nplb/system_hide_splash_screen_test.cc
Labels: on_device

#3236 Migrate Cobalt Core to pthread
  cobalt/base/log_message_handler.cc
  cobalt/dom/serialized_algorithm_runner.h
  cobalt/loader/fetcher_cache.cc
  cobalt/loader/fetcher_cache.h
  third_party/abseil-cpp/absl/base/internal/sysinfo_starboard.cc
  third_party/skia/src/core/SkThreadID.cpp
  v8/src/base/platform/platform-starboard.cc
Labels: on_device

#3237 Migrate starboard/share to pthread
  starboard/shared/libevent/socket_waiter_internal.cc
  starboard/shared/libevent/socket_waiter_internal.h
  starboard/shared/starboard/application.cc
  starboard/shared/starboard/application.h
  starboard/shared/starboard/player/job_queue.cc
  starboard/shared/starboard/player/job_queue.h
  starboard/shared/starboard/thread_checker.h
Labels: on_device

#3235 Migrate starboard/common to pthread
  starboard/common/log.cc
  starboard/common/mutex.cc
  starboard/common/mutex.h
  starboard/common/recursive_mutex.cc
  starboard/common/recursive_mutex.h
  starboard/common/thread_collision_warner.cc
Labels: on_device

#3238 Migrate the SbThreadSampler to pthread
  starboard/CHANGELOG.md
  starboard/nplb/thread_sampler_test.cc
  starboard/shared/pthread/thread_sampler_create.cc
  starboard/shared/pthread/thread_sampler_internal.cc
  starboard/shared/pthread/thread_sampler_internal.h
  starboard/shared/stub/thread_sampler_create.cc
  starboard/thread.h
  third_party/musl/src/include/pthread.h
  v8/src/libsampler/sampler.cc
Labels: on_device

#3246 [media] Refine write_head_ handling in ChunkDemuxerStream
  media/filters/chunk_demuxer.cc
Labels: runtest, cp-25.lts.1+

#3322 Change Android DPad key mapping
  starboard/android/shared/input_events_generator.cc
Labels: cp-25.lts.1+

#3323 Set test runner default return to be error
  starboard/tools/testing/test_runner.py
Labels: on_device

#3351 Simplify the pthread_cond_timedwait management.
  starboard/nplb/posix_compliance/posix_condition_variable_wait_timed_test.cc
  starboard/shared/modular/starboard_layer_posix_pthread_abi_wrappers.cc
  starboard/shared/win32/posix_emu/pthread.cc
  starboard/win/shared/configuration_public.h
  starboard/xb1/shared/configuration_public.h
Labels: on_device

#3341 Filter flaky tests
  cobalt/build/cobalt_configuration.py
  starboard/android/shared/cobalt/configuration.py
  starboard/linux/shared/cobalt/configuration.py
  starboard/win/win32/cobalt/configuration.py
Labels: on_device

#3356 [android] Fix crash on VideoDecoder::Reset() when |media_decoder_| is NULL
  starboard/android/shared/audio_decoder.cc
  starboard/android/shared/video_decoder.cc
Labels: on_device

#3357 Migrate to pthread_mutex/pthread_cond
  base/logging.cc
  base/synchronization/condition_variable.h
  base/synchronization/condition_variable_starboard.cc
  base/synchronization/lock_impl.h
  base/synchronization/lock_impl_starboard.cc
  cobalt/renderer/rasterizer/skia/skia/src/ports/SkMutex_starboard.h
  starboard/android/shared/log_format.cc
  starboard/common/condition_variable.cc
  starboard/common/condition_variable.h
  starboard/common/mutex.cc
  starboard/common/mutex.h
  starboard/common/rwlock.cc
  starboard/common/rwlock.h
  starboard/nplb/condition_variable_broadcast_test.cc
  starboard/nplb/condition_variable_create_test.cc
  starboard/nplb/condition_variable_signal_test.cc
  starboard/nplb/thread_helpers.h
  starboard/shared/pthread/condition_variable_broadcast.cc
  starboard/shared/pthread/condition_variable_create.cc
  starboard/shared/pthread/condition_variable_destroy.cc
  starboard/shared/pthread/condition_variable_signal.cc
  starboard/shared/pthread/condition_variable_wait_timed.cc
  starboard/tools/api_leak_detector/api_leak_detector.py
  third_party/boringssl/src/crypto/thread_starboard.cc
  third_party/boringssl/src/include/openssl/thread.h
  third_party/llvm-project/libcxx/include/__external_threading
  third_party/musl/src/exit/atexit.c
  v8/src/base/platform/condition-variable.cc
  v8/src/base/platform/condition-variable.h
  v8/src/base/platform/mutex.cc
  v8/src/base/platform/mutex.h
Labels: on_device

#3364 Webdriver: fix window ID parsing
  cobalt/webdriver/BUILD.gn
  cobalt/webdriver/dispatcher_test.cc
  cobalt/webdriver/protocol/log_type.cc
  cobalt/webdriver/protocol/window_id.cc
  cobalt/webdriver/util/dispatch_command_factory.h
Labels: cp-24.lts.1+, on_device

#3370 Apply v8 fix on heap/scavenger.cc
  v8/src/heap/scavenger.cc
Labels: on_device
