Repository youtube/cobalt, pull requests merged in 2024-08, with the labels that each got.

#3919 Add SB17 builders
  .github/config/evergreen-arm-hardfp.json
  .github/config/evergreen-arm-softfp.json
  .github/config/evergreen-arm64.json
  .github/config/evergreen-x64.json
  .github/config/linux.json
  .github/config/raspi-2.json
  starboard/tools/api_leak_detector/api_leak_detector.py
Labels: on_device

#3923 Revert "Default quic to on for all platforms"
  cobalt/network/url_request_context.cc
Labels: cp-25.lts.1+

#3930 Exclude unsupported getaddrinfo flags
  starboard/nplb/posix_compliance/posix_socket_resolve_test.cc
Labels: on_device

#3943 Disable CORS preflight request upon command line flag
  cobalt/loader/cors_preflight.cc
Labels: cp-24.lts.1+

#3939 Print an error message and return instead of crash
  starboard/elf_loader/exported_symbols.cc
  starboard/elf_loader/exported_symbols.h
Labels: cp-25.lts.1+

#3897 Remove SB14 references
  cobalt/media/base/sbplayer_pipeline.cc
  media/base/starboard_utils.cc
  starboard/android/shared/BUILD.gn
  starboard/android/shared/configuration_constants.cc
  starboard/common/media.cc
  starboard/configuration_constants.h
  starboard/elf_loader/exported_symbols.cc
  starboard/linux/shared/BUILD.gn
  starboard/linux/shared/configuration_constants.cc
  starboard/linux/shared/media_is_audio_supported.cc
  starboard/media.h
  starboard/memory.h
  starboard/memory_reporter.h
  starboard/nplb/extern_c_test.cc
  starboard/nplb/include_all.c
  starboard/nplb/media_set_audio_write_duration_test.cc
  starboard/raspi/shared/BUILD.gn
  starboard/raspi/shared/configuration_constants.cc
  starboard/shared/ffmpeg/ffmpeg_audio_decoder_impl.cc
  starboard/shared/linux/memory_get_stack_bounds.cc
  starboard/shared/starboard/media/codec_util.cc
  starboard/shared/starboard/media/codec_util_test.cc
  starboard/shared/starboard/media/parsed_mime_info_test.cc
  starboard/shared/starboard/memory.cc
  starboard/shared/starboard/player/filter/testing/audio_decoder_test.cc
  starboard/shared/stub/media_set_audio_write_duration.cc
  starboard/shared/stub/memory_get_stack_bounds.cc
  starboard/stub/BUILD.gn
  starboard/stub/configuration_constants.cc
  starboard/win/shared/BUILD.gn
  starboard/win/shared/configuration_constants.cc
  starboard/xb1/BUILD.gn
  starboard/xb1/shared/configuration_constants.cc
Labels: on_device

#3899 Remove refs to SbPlayerSeek2, SbPlayerGetInfo2, SbPlayerWriteSample2
  cobalt/media/base/sbplayer_bridge.cc
  cobalt/media/base/sbplayer_interface.cc
  cobalt/media/base/sbplayer_interface.h
  starboard/elf_loader/exported_symbols.cc
  starboard/linux/shared/BUILD.gn
  starboard/linux/shared/system_get_extensions.cc
  starboard/nplb/media_set_audio_write_duration_test.cc
  starboard/nplb/player_test_fixture.cc
  starboard/nplb/player_test_util.cc
  starboard/player.h
  starboard/shared/enhanced_audio/enhanced_audio.cc
  starboard/shared/enhanced_audio/enhanced_audio.gni
  starboard/shared/enhanced_audio/enhanced_audio.h
  starboard/shared/enhanced_audio/enhanced_audio_player_write_samples.cc
  starboard/shared/enhanced_audio/enhanced_audio_player_write_samples.h
  starboard/shared/enhanced_audio/player_write_samples_checked.cc
  starboard/shared/starboard/player/player_get_info.cc
  starboard/shared/starboard/player/player_internal.cc
  starboard/shared/starboard/player/player_internal.h
  starboard/shared/starboard/player/player_seek.cc
  starboard/shared/starboard/player/player_write_samples.cc
  starboard/shared/stub/player_get_info.cc
  starboard/shared/stub/player_seek.cc
  starboard/shared/stub/player_write_samples.cc
Labels: on_device

#3895 Remove SbSystemGetDeviceType
  cobalt/browser/application.cc
  cobalt/browser/user_agent_platform_info.cc
  cobalt/browser/user_agent_platform_info.h
  cobalt/web/testing/mock_user_agent_platform_info.h
  cobalt/web/user_agent_platform_info.h
  starboard/android/shared/BUILD.gn
  starboard/android/shared/system_get_device_type.cc
  starboard/elf_loader/exported_symbols.cc
  starboard/linux/shared/BUILD.gn
  starboard/linux/shared/system_get_device_type.cc
  starboard/nplb/system_get_property_test.cc
  starboard/raspi/shared/BUILD.gn
  starboard/raspi/shared/system_get_device_type.cc
  starboard/shared/stub/system_get_device_type.cc
  starboard/shared/uwp/application_uwp.cc
  starboard/shared/uwp/player_components_factory.cc
  starboard/shared/uwp/system_get_device_type.cc
  starboard/shared/win32/system_get_device_type.cc
  starboard/stub/BUILD.gn
  starboard/system.h
  starboard/win/win32/BUILD.gn
  starboard/xb1/BUILD.gn
Labels: on_device

#3972 Prioritize IPv4 addresses over IPv6
  net/dns/address_sorter_posix.cc
  net/dns/address_sorter_posix_unittest.cc
Labels: on_device

#3982 Fix C25 xbox build failure on SbFileOpen.
  starboard/shared/win32/file_open.cc
Labels: on_device, cp-25.lts.1+

#3944 Code clean up to remove starboard/common/atomic usage
  chrome/updater/configurator.h
  starboard/android/shared/android_main.cc
  starboard/android/shared/application_android.h
  starboard/android/shared/audio_renderer_passthrough.h
  starboard/android/shared/drm_system.cc
  starboard/android/shared/drm_system.h
  starboard/android/shared/egl_swap_buffers.cc
  starboard/android/shared/media_codec_bridge_eradicator.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/player_components_factory.h
  starboard/android/shared/video_decoder.h
  starboard/common/thread.cc
  starboard/common/thread.h
  starboard/nplb/player_test_util.cc
  starboard/nplb/thread_sampler_test.cc
  starboard/nplb/thread_test.cc
  starboard/shared/pulse/pulse_audio_sink_type.cc
  starboard/shared/starboard/link_receiver.cc
  starboard/shared/starboard/net_log.cc
  starboard/shared/starboard/player/filter/audio_renderer_internal_pcm.cc
  starboard/shared/starboard/player/filter/audio_renderer_internal_pcm.h
  starboard/shared/starboard/player/filter/punchout_video_renderer_sink.h
  starboard/shared/starboard/player/filter/video_renderer_internal_impl.cc
  starboard/shared/starboard/player/filter/video_renderer_internal_impl.h
  starboard/shared/starboard/queue_application.cc
  starboard/shared/uwp/audio_renderer_passthrough.h
  starboard/shared/uwp/extended_resources_manager.h
  starboard/shared/uwp/microphone_impl.cc
  starboard/shared/uwp/wasapi_audio.cc
  starboard/shared/uwp/wasapi_audio_sink.h
  starboard/shared/widevine/drm_system_widevine.h
  starboard/shared/win32/audio_decoder_thread.cc
  starboard/shared/win32/audio_decoder_thread.h
  starboard/shared/win32/socket_internal.h
  starboard/shared/win32/win32_audio_decoder.cc
  starboard/xb1/shared/gpu_base_video_decoder.h
Labels: on_device

#3960 Remove windows github infra
  .github/actions/docker_win/action.yaml
  .github/config/win32.json
  .github/config/xb1.json
  .github/workflows/main_win.yaml
  .github/workflows/nightly_trigger.yaml
  .github/workflows/pr_badges.yaml
  .github/workflows/win32.yaml
  .github/workflows/workflow_trigger.yaml
  .github/workflows/xb1.yaml
Labels: runtest

#4010 Fix the readdir_r wrapping for Evergreen SB16
  starboard/elf_loader/exported_symbols.cc
Labels: on_device

#4011 Optimize for speed in boringssl
  third_party/boringssl/BUILD.gn
Labels: runtest, cp-25.lts.1+

#3941 Add posix compliance test for sscanf.
  starboard/nplb/BUILD.gn
  starboard/nplb/posix_compliance/posix_string_scan_test.cc
Labels: on_device

#4012 Deprecate SbFile, SbFileError, SbFileInfo types.
  base/files/file.h
  base/files/file_starboard.cc
  base/memory/platform_shared_memory_handle.h
  net/cert/internal/trust_store_in_memory_starboard.cc
  starboard/nplb/posix_compliance/posix_directory_open_test.cc
  starboard/shared/win32/file_internal.cc
  starboard/shared/win32/file_internal.h
  starboard/shared/win32/log_file_impl.cc
  starboard/shared/win32/minidump.cc
  starboard/shared/win32/posix_emu/dirent.cc
  third_party/libjpeg_turbo/BUILD.gn
  third_party/libjpeg_turbo/cdjpeg.h
  third_party/libjpeg_turbo/jmemsys.h
  third_party/libjpeg_turbo/jpeglib.h
Labels: on_device, cp-25.lts.1+

#4046 [android] Rename max_output_buffers_lookup_table.*
  starboard/android/shared/BUILD.gn
  starboard/android/shared/max_media_codec_output_buffers_lookup_table.cc
  starboard/android/shared/max_media_codec_output_buffers_lookup_table.h
  starboard/android/shared/media_is_video_supported.cc
  starboard/android/shared/video_decoder.h
Labels: cp-24.lts.1+, cp-25.lts.1+

#4047 Add media_support_internal to media_util gn target
  starboard/shared/starboard/media/BUILD.gn
  starboard/stub/BUILD.gn
Labels: cp-24.lts.1+, cp-25.lts.1+

#4055 Deprecate SbFile types.
  starboard/file.h
  starboard/shared/win32/file_internal.cc
  starboard/shared/win32/file_internal.h
Labels: on_device
