Repository youtube/cobalt, pull requests merged in 2025-05, with the labels that each got.

#5549 Wire up H5vccMetrics
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_browser_main_parts.cc
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/browser/global_features.cc
  cobalt/browser/global_features.h
  cobalt/browser/h5vcc_metrics/BUILD.gn
  cobalt/browser/h5vcc_metrics/h5vcc_metrics_impl.cc
  cobalt/browser/h5vcc_metrics/h5vcc_metrics_impl.h
  cobalt/browser/h5vcc_metrics/public/mojom/h5vcc_metrics.mojom
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.cc
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.h
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.h
  third_party/blink/renderer/bindings/generated_in_modules.gni
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.h
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/metrics_event.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/metrics_event.h
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/metrics_event.idl
  third_party/metrics_proto/BUILD.gn
  third_party/metrics_proto/cobalt_uma_event.proto
Labels: cp-26.android

#5587 [Refactor] Use make_unique instead of raw new
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/video_decoder.cc
  starboard/shared/starboard/player/filter/player_components.cc
Labels: cp-26.android

#5634 Remove unnecessary CHECK
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
Labels: cp-26.android

#5635 Early return for UMA service type.
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.cc
Labels: cp-26.android

#5645 Fixes bug with UMA logs uploader across page refreshes.
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.cc
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.h
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.h
Labels: cp-26.android

#5646 Persist UMA enablement state across app lifecycles.
  cobalt/BUILD.gn
  cobalt/browser/cobalt_browser_main_parts.cc
  cobalt/browser/global_features.cc
  cobalt/browser/global_features.h
  cobalt/browser/h5vcc_metrics/h5vcc_metrics_impl.cc
  cobalt/browser/metrics/cobalt_enabled_state_provider.cc
  cobalt/browser/metrics/cobalt_enabled_state_provider.h
  cobalt/browser/metrics/cobalt_enabled_state_provider_test.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
Labels: cp-26.android

#5190 Add h5vcc experiment APIs.
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_browser_interface_binders.cc
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/browser/cobalt_experiment_names.h
  cobalt/browser/global_features.cc
  cobalt/browser/global_features.h
  cobalt/browser/h5vcc_experiments/BUILD.gn
  cobalt/browser/h5vcc_experiments/h5vcc_experiments_impl.cc
  cobalt/browser/h5vcc_experiments/h5vcc_experiments_impl.h
  cobalt/browser/h5vcc_experiments/public/mojom/BUILD.gn
  cobalt/browser/h5vcc_experiments/public/mojom/h5vcc_experiments.mojom
  content/web_test/BUILD.gn
  third_party/blink/renderer/bindings/generated_in_modules.gni
  third_party/blink/renderer/bindings/idl_in_modules.gni
  third_party/blink/renderer/modules/BUILD.gn
  third_party/blink/renderer/modules/cobalt/BUILD.gn
  third_party/blink/renderer/modules/cobalt/h5vcc_experiments/BUILD.gn
  third_party/blink/renderer/modules/cobalt/h5vcc_experiments/h_5_vcc_experiments.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_experiments/h_5_vcc_experiments.h
  third_party/blink/renderer/modules/cobalt/h5vcc_experiments/h_5_vcc_experiments.idl
  third_party/blink/renderer/modules/cobalt/h_5_vcc.cc
  third_party/blink/renderer/modules/cobalt/h_5_vcc.h
  third_party/blink/renderer/modules/cobalt/h_5_vcc.idl
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/h5vcc-experiments-getfeature.https.any.js
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/h5vcc-experiments-getfeatureparam.https.any.js
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/h5vcc-experiments-resetExperimentState.https.any.js
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/h5vcc-experiments-setExperimentState.https.any.js
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/resources/automation.js
  third_party/blink/web_tests/wpt_internal/cobalt/h5vcc-experiments/resources/mock-h5vcc-experiments.js
Labels: cp-26.android

#5701 [media] Recapture DecoderBufferAllocator test files
  media/test/data/starboard/allocations_1La4QzGeaaQ.txt
  media/test/data/starboard/allocations_PMwaIrjiz8w.txt
Labels: on_device, cp-26.android

#5691 Build nplb_evergreen_compat_tests with default toolchain
  starboard/BUILD.gn
Labels: on_device

#5718 Fix kAVFormatDoesNotHaveRegisterAll.
  starboard/shared/ffmpeg/ffmpeg_dispatch.h
  starboard/shared/ffmpeg/ffmpeg_dynamic_load_dispatch_impl.cc
Labels: cp-26.android

#5679 Add CobaltMetricsService* unit tests
  cobalt/BUILD.gn
  cobalt/browser/BUILD.gn
  cobalt/browser/metrics/cobalt_metrics_logs_uploader.h
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_service_client_test.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client_test.cc
Labels: cp-26.android

#5717 Install ffmpeg on unittest image and re-enable unittests
  cobalt/docker/unittest/Dockerfile
  starboard/linux/shared/BUILD.gn
  starboard/shared/starboard/media/media_util.cc
  starboard/shared/starboard/media/media_util.h
  starboard/shared/starboard/player/filter/testing/BUILD.gn
  starboard/shared/starboard/player/filter/testing/adaptive_audio_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/audio_decoder_test.cc
  starboard/shared/starboard/player/filter/testing/player_components_test.cc
Labels: cp-26.android

#5648 Implement custom API for HTMLVideoElement
  third_party/blink/public/platform/web_media_player_client.h
  third_party/blink/renderer/bindings/idl_in_core.gni
  third_party/blink/renderer/core/BUILD.gn
  third_party/blink/renderer/core/cobalt/build.gni
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions.cc
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions.h
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions.idl
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions_test.cc
  third_party/blink/renderer/core/html/media/html_video_element.cc
  third_party/blink/renderer/core/html/media/html_video_element.h
  third_party/blink/web_tests/wpt_internal/cobalt/HTMLVideoElementExtension/getAndSetMaxVideoCapabilities.html
Labels: cp-26.android

#5751 Fix memory leak in cobalt_metrics_services_manager.
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_service_client_test.cc
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
Labels: cp-26.android

#5673 Print test result summary in logs job
  .github/actions/print_logs/action.yaml
  .github/actions/process_test_results/action.yaml
  .github/workflows/main.yaml
  cobalt/tools/junit_mini_parser.py
  cobalt/tools/junit_mini_parser_test.py
Labels: on_device

#5740 Reduce decoded image cache size to 32 mb
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
  cobalt/cobalt_switch_defaults.cc
Labels: on_device, cp-26.android

#5764 Fix UMA idle bug.
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_service_client_test.cc
Labels: cp-26.android

#5770 Add UMA histogram metadata XML files.
  tools/metrics/histograms/metadata/cobalt/enums.xml
  tools/metrics/histograms/metadata/cobalt/histograms.xml
Labels: runtest, cp-26.android

#5784 [Cleanup] Remove duplicated log
  media/starboard/starboard_cdm.cc
Labels: cp-26.android

#5780 Enable 4k/8k playback on linux-x64x11
  starboard/linux/shared/media_is_video_supported.cc
  starboard/linux/shared/player_components_factory.cc
  starboard/shared/libdav1d/dav1d_video_decoder.cc
  starboard/shared/libdav1d/dav1d_video_decoder.h
Labels: on_device

#5627 [media] Optimize DecoderBufferAllocator
  media/base/media_switches.cc
  media/base/media_switches.h
  media/starboard/BUILD.gn
  media/starboard/bidirectional_fit_reuse_allocator.cc
  media/starboard/bidirectional_fit_reuse_allocator.h
  media/starboard/bidirectional_fit_reuse_allocator_test.cc
  media/starboard/decoder_buffer_allocator.cc
  media/starboard/decoder_buffer_allocator_strategy.cc
  media/starboard/decoder_buffer_allocator_strategy.h
  media/starboard/decoder_buffer_allocator_test.cc
  starboard/common/BUILD.gn
  starboard/common/allocator.cc
  starboard/common/in_place_reuse_allocator_base.cc
  starboard/common/in_place_reuse_allocator_base.h
  starboard/common/reuse_allocator_base.cc
Labels: on_device, cp-26.android

#5798 [Refactor] Use dedicated ctor for Success/Failure UpdateSessionResult
  cobalt/android/apk/app/src/main/java/dev/cobalt/media/MediaDrmBridge.java
Labels: cp-26.android

#5756 [media] Send maxVideoCapabilities to StarboardRenderer
  content/renderer/media/media_factory.cc
  content/renderer/media/media_factory.h
  media/base/ipc/media_param_traits_macros.h
  media/base/starboard/renderer_factory_traits.h
  media/base/starboard/starboard_renderer_config.cc
  media/base/starboard/starboard_renderer_config.h
  media/base/starboard/starboard_renderer_config_unittest.cc
  media/mojo/clients/starboard/starboard_renderer_client_factory.cc
  media/mojo/clients/starboard/starboard_renderer_client_factory.h
  media/mojo/services/gpu_mojo_media_client.cc
  media/mojo/services/gpu_mojo_media_client.h
  media/mojo/services/media_service_unittest.cc
  media/mojo/services/starboard/starboard_renderer_wrapper.cc
  media/starboard/starboard_renderer.cc
  media/starboard/starboard_renderer.h
Labels: cp-26.android

#5801 Resolve H5vccMetrics Promises on connection close.
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.h
Labels: cp-26.android

#5854 Removes license file generation from CI
  .github/actions/build/action.yaml
  cobalt/build/android/package.json
  cobalt/build/linux/package.json
  cobalt/devinfra/kokoro/bin/dind_build.sh
Labels: cp-26.android

#5689 Add support for running RDK tests using `starboard/tools/testing/test_runner.py`
  starboard/evergreen/shared/launcher.py
  starboard/raspi/shared/launcher.py
  starboard/rdk/gyp_configuration.py
  starboard/rdk/launcher.py
  starboard/rdk/test_filters.py
Labels: on_device

#5855 Add Cobalt.apk to uncompressed release package
  cobalt/build/android/package.json
Labels: cp-26.android

#5827 [media] [cleanup] Tidy up maxVideoCapabilities implementation
  content/renderer/media/media_factory.cc
  third_party/blink/public/platform/web_media_player_client.h
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions.cc
  third_party/blink/renderer/core/cobalt/html_video_element/html_video_element_extensions_test.cc
  third_party/blink/renderer/core/html/media/html_video_element.cc
  third_party/blink/renderer/core/html/media/html_video_element.h
Labels: cp-26.android

#5923 Refine usage of StarboardRenderer in its wrapper
  media/mojo/services/gpu_mojo_media_client.cc
  media/mojo/services/gpu_mojo_media_client.h
  media/mojo/services/starboard/gpu_mojo_media_client_starboard.cc
  media/mojo/services/starboard/starboard_renderer_wrapper.cc
  media/mojo/services/starboard/starboard_renderer_wrapper.h
Labels: on_device, cp-26.android
