Repository youtube/cobalt, pull requests merged in 2025-03, with the labels that each got.

#4984 Avoid running starboard code during nplb init
  cobalt/testing/filters/linux-x64x11/nplb_filter.json
  starboard/nplb/media_set_audio_write_duration_test.cc
  starboard/nplb/multiple_player_test.cc
  starboard/nplb/player_get_audio_configuration_test.cc
  starboard/nplb/player_get_media_time_test.cc
  starboard/nplb/player_test_util.cc
  starboard/nplb/player_test_util.h
  starboard/nplb/player_write_sample_test.cc
Labels: on_device

#4994 Fix rpi docker build
  docker/linux/raspi/Dockerfile
Labels: outside collaborator

#4835 Refine SbPlayerGetMediaTimeTest
  starboard/android/shared/test_filters.py
  starboard/nplb/player_get_media_time_test.cc
  starboard/win/win32/test_filters.py
Labels: on_device

#4987 [Ozone] Disable all non-starboard backends
  cobalt/build/configs/linux-x64x11-evergreen/args.gn
  cobalt/build/configs/linux-x64x11/args.gn
  cobalt/build/configs/linux_common.gn
  cobalt/build/gn.py
  cobalt/build/testing/targets/linux-x64x11/test_targets.json
  cobalt/cobalt_switch_defaults.cc
  cobalt/cobalt_switch_defaults_test.cc
  cobalt/testing/filters/linux-x64x11/cc_unittests_filter.json
  cobalt/testing/filters/linux-x64x11/viz_unittests_filter.json
  ui/ozone/platform/starboard/ozone_platform_starboard.cc
Labels: on_device

#5078 Disable Swiftshader for Linux
  cobalt/build/configs/linux_common.gn
Labels: runtest

#5097 Remove condition for angle_use_x11 flag
  cobalt/build/configs/linux-x64x11-evergreen/args.gn
  cobalt/build/configs/linux-x64x11/args.gn
Labels: on_device

#5107 Remove default variant from raspi-2 and EG builders.
  .github/config/evergreen-arm-hardfp.json
  .github/config/evergreen-arm-softfp.json
  .github/config/evergreen-arm64.json
  .github/config/evergreen-x64.json
  .github/config/linux.json
  .github/config/raspi-2.json
Labels: on_device

#5102 Use TrustedHeaderClient to add Cobalt Client Hint header
  cobalt/browser/BUILD.gn
  cobalt/browser/client_hint_headers/BUILD.gn
  cobalt/browser/client_hint_headers/cobalt_header_value_provider.cc
  cobalt/browser/client_hint_headers/cobalt_header_value_provider.h
  cobalt/browser/client_hint_headers/cobalt_trusted_header_client.cc
  cobalt/browser/client_hint_headers/cobalt_trusted_header_client.h
  cobalt/browser/client_hint_headers/cobalt_trusted_url_loader_header_client.cc
  cobalt/browser/client_hint_headers/cobalt_trusted_url_loader_header_client.h
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/browser/cobalt_content_browser_client.h
  services/network/url_loader.cc
Labels: on_device

#5130 Revert dynamic test target calculation
  .github/actions/build/action.yaml
  cobalt/build/testing/targets/android-arm/test_targets.json
  cobalt/build/testing/targets/android-arm64/test_targets.json
  cobalt/build/testing/targets/linux-x64x11/test_targets.json
  cobalt/testing/filters/linux-x64x11/wm_unittests_filter.json
Labels: on_device

#5123 Enable an is_cobalt build of content_shell
  cobalt/build/configs/linux-x64x11-no-starboard/args.gn
  cobalt/build/gn.py
  content/public/common/BUILD.gn
  content/web_test/BUILD.gn
  media/base/cdm_context.h
  media/base/mime_util_internal.cc
  media/media_options.gni
  media/starboard/BUILD.gn
  starboard/shared/toolchain/overridable_gcc_toolchain.gni
  third_party/blink/renderer/bindings/idl_in_modules.gni
  third_party/blink/renderer/core/html/media/html_media_element.cc
  third_party/blink/renderer/modules/cobalt/BUILD.gn
  third_party/blink/renderer/modules/cobalt/encryptedmedia/BUILD.gn
  third_party/blink/renderer/modules/cobalt/h5vcc_metrics/h_5_vcc_metrics.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_storage/h_5_vcc_storage.cc
  third_party/blink/renderer/modules/cobalt/h5vcc_storage/testing/h_5_vcc_storage_for_testing.cc
  third_party/blink/renderer/modules/cobalt/mediasource/BUILD.gn
  third_party/blink/renderer/modules/mediasource/media_source.cc
  third_party/blink/renderer/platform/media/key_system_config_selector.cc
  third_party/blink/web_tests/wpt_internal/cobalt/crash-log/resources/automation.js
  ui/ozone/BUILD.gn
Labels: on_device

#5174 Refactor CobaltBrowserMainParts into its own file.
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_browser_main_parts.cc
  cobalt/browser/cobalt_browser_main_parts.h
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
Labels: on_device

#5183 Add binder for H5vccRuntime to fix other web tests
  cobalt/testing/h5vcc_runtime/BUILD.gn
  cobalt/testing/h5vcc_runtime/stub_h5vcc_runtime_impl.cc
  cobalt/testing/h5vcc_runtime/stub_h5vcc_runtime_impl.h
  content/web_test/BUILD.gn
  content/web_test/browser/web_test_content_browser_client.cc
  content/web_test/browser/web_test_content_browser_client.h
Labels: on_device

#5226 Add web api for used device memory
  cobalt/browser/performance/performance_impl.cc
  cobalt/browser/performance/performance_impl.h
  cobalt/browser/performance/public/mojom/performance.mojom
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.cc
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.h
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.idl
Labels: cp-26.android
