Repository youtube/cobalt, pull requests merged in 2025-06, with the labels that each got.

#5897 Fix missing Feature flags initialization
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_content_browser_client.cc
  components/variations/service/variations_field_trial_creator.h
Labels: runtest, cp-26.android

#6007 [android] Refine MediaDecoder thread termination
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
Labels: on_device

#6000 [android] Explicitly enable KEY_TUNNEL_PEEK
  cobalt/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
Labels: cp-26.android

#6019 [Refactor] Replace starboard::mutex in starboard/android
  starboard/android/shared/asset_manager.cc
  starboard/android/shared/asset_manager.h
  starboard/android/shared/audio_decoder.cc
  starboard/android/shared/audio_decoder.h
  starboard/android/shared/audio_renderer_passthrough.cc
  starboard/android/shared/audio_renderer_passthrough.h
  starboard/android/shared/audio_track_audio_sink_type.cc
  starboard/android/shared/audio_track_audio_sink_type.h
  starboard/android/shared/continuous_audio_track_sink.cc
  starboard/android/shared/continuous_audio_track_sink.h
  starboard/android/shared/max_media_codec_output_buffers_lookup_table.cc
  starboard/android/shared/max_media_codec_output_buffers_lookup_table.h
  starboard/android/shared/microphone_impl.cc
  starboard/android/shared/posix_emu/dirent.cc
  starboard/android/shared/video_frame_tracker.cc
  starboard/android/shared/video_frame_tracker.h
  starboard/android/shared/video_window.cc
Labels: cp-26.android

#5834 Improve log message of starboard_cdm
  media/starboard/starboard_cdm.cc
  media/starboard/starboard_cdm.h
  media/starboard/starboard_cdm_factory.cc
  starboard/common/BUILD.gn
  starboard/common/drm.cc
  starboard/common/drm.h
  starboard/common/drm_test.cc
Labels: cp-26.android

#6067 Fix CobaltMetricsLogUploader file naming
  cobalt/BUILD.gn
  cobalt/browser/BUILD.gn
  cobalt/browser/metrics/cobalt_metrics_log_uploader.cc
  cobalt/browser/metrics/cobalt_metrics_log_uploader.h
  cobalt/browser/metrics/cobalt_metrics_log_uploader_test.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_service_client_test.cc
Labels: cp-26.android

#6134 [atv] Refine type/function names in MediaDecoder
  starboard/android/shared/audio_decoder.cc
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/media_decoder.h
  starboard/android/shared/video_decoder.cc
Labels: on_device

#6038 [Cleanup] Remove `starboard/.../concurrency_debug.h`
  starboard/common/BUILD.gn
  starboard/common/experimental/concurrency_debug.cc
  starboard/common/experimental/concurrency_debug.h
Labels: cp-26.android

#6148 Add unit test for Queue and Semaphore
  starboard/common/BUILD.gn
  starboard/common/queue.h
  starboard/common/queue_test.cc
  starboard/common/semaphore_test.cc
Labels: cp-26.android

#6039 [Refactor] Replace starboard::mutex in starboad codecs
  starboard/shared/ffmpeg/ffmpeg_video_decoder_impl.cc
  starboard/shared/ffmpeg/ffmpeg_video_decoder_impl.h
  starboard/shared/libaom/aom_video_decoder.cc
  starboard/shared/libaom/aom_video_decoder.h
  starboard/shared/libdav1d/dav1d_video_decoder.cc
  starboard/shared/libdav1d/dav1d_video_decoder.h
  starboard/shared/libde265/de265_video_decoder.cc
  starboard/shared/libde265/de265_video_decoder.h
  starboard/shared/libvpx/vpx_video_decoder.cc
  starboard/shared/libvpx/vpx_video_decoder.h
  starboard/shared/speechd/speechd_internal.cc
  starboard/shared/speechd/speechd_internal.h
Labels: cp-26.android

#6196 Modify build targets in draft_build.md
  cobalt/doc/draft_build.md
Labels: outside collaborator

#6157 Make all JNI method calls to StarboardBridge go through starboard_bridge.h
  starboard/android/shared/platform_info.cc
  starboard/android/shared/starboard_bridge.cc
  starboard/android/shared/starboard_bridge.h
  starboard/android/shared/system_get_property.cc
Labels: cp-26.android

#6223 [android] Enable media_unittests
  cobalt/build/testing/targets/android-arm/test_targets.json
  cobalt/build/testing/targets/android-arm64/test_targets.json
  cobalt/testing/filters/android-arm/media_unittests_filter.json
  cobalt/testing/filters/android-arm64/media_unittests_filter.json
Labels: on_device
