Repository youtube/cobalt, pull requests merged in 2025-02, with the labels that each got.

#4829 Fix dimensions
  .github/actions/on_device_tests/action.yaml
  .github/config/android-arm.json
  .github/workflows/main.yaml
  cobalt/tools/on_device_tests_gateway_client.py
Labels: runtest, on_device

#4821 Enable on-device unit tests on android-arm64
  .github/config/android-arm64.json
  cobalt/build/testing/targets/android-arm64/test_targets.json
  cobalt/testing/filters/android-arm64/sql_unittests_filter.json
Labels: on_device

#4815 Add print logs step
  .github/actions/build/action.yaml
  .github/actions/on_device_tests/action.yaml
  .github/actions/on_host_tests/action.yaml
  .github/actions/process_test_results/action.yaml
  .github/workflows/main.yaml
Labels: on_device

#4840 Expose window.internals when enabled by flag
  cobalt/renderer/BUILD.gn
  cobalt/renderer/cobalt_content_renderer_client.cc
  cobalt/renderer/cobalt_render_frame_observer.cc
  cobalt/renderer/cobalt_render_frame_observer.h
Labels: runtest, on_device

#4842 Ignore log settings on device
  base/android/java/src/org/chromium/base/Log.java
Labels: on_device

#4886 ODT Gateway - fix timeout_sec arg
  cobalt/tools/on_device_tests_gateway_client.py
Labels: runtest, on_device

#4867 Fix concurrency setting
  .github/workflows/main.yaml
  .github/workflows/workflow_debug.yaml
Labels: on_device

#4888 Migrate all inner classes in MediaCodecBridge to jni_generator
  cobalt/android/apk/app/src/main/java/dev/cobalt/media/MediaCodecBridge.java
  starboard/android/shared/media_codec_bridge.cc
Labels: on_device

#4907 Add flag to fix shield rendering
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
Labels: on_device

#4824 Hide symbols in libunwind configuration used by Starboard
  third_party/llvm-project/libunwind/BUILD.gn
Labels: on_device, outside collaborator

#4855 Package dependencies from source dir for android
  .github/actions/upload_test_artifacts/action.yaml
  cobalt/build/archive_test_artifacts.py
  cobalt/testing/filters/android-arm/sql_unittests_filter.json
Labels: on_device

#4826 Increase pread() offset range to fix symbolization on 32-bit systems
  third_party/symbolize/symbolize.cc
Labels: on_device, outside collaborator

#4823 Fix IS_EVERGREEN_ADDRESS macro
  starboard/elf_loader/evergreen_info.h
Labels: runtest, on_device, outside collaborator

#4838 Re-add MediaSession java source code
  cobalt/android/BUILD.gn
  cobalt/android/apk/apk_sources.gni
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/ArtworkDownloaderDefault.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/ArtworkLoader.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltMediaSession.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/MediaImage.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/StarboardBridge.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/media/AudioOutputManager.java
Labels: on_device

#4911 Fix test results bugs
  .github/actions/process_test_results/action.yaml
  .github/workflows/main.yaml
Labels: on_device

#4891 Update all ScopedLocalJavaRef variables to ScopedJavaLocalRef in MediaCodecBridge
  starboard/android/shared/media_codec_bridge.cc
Labels: on_device

#4936 Rename crashAnnotator web interface as crashLog
  third_party/blink/renderer/bindings/generated_in_modules.gni
  third_party/blink/renderer/bindings/idl_in_modules.gni
  third_party/blink/renderer/modules/BUILD.gn
  third_party/blink/renderer/modules/cobalt/BUILD.gn
  third_party/blink/renderer/modules/cobalt/crash_log/BUILD.gn
  third_party/blink/renderer/modules/cobalt/crash_log/crash_log.cc
  third_party/blink/renderer/modules/cobalt/crash_log/crash_log.h
  third_party/blink/renderer/modules/cobalt/crash_log/crash_log.idl
  third_party/blink/renderer/modules/cobalt/h_5_vcc.cc
  third_party/blink/renderer/modules/cobalt/h_5_vcc.h
  third_party/blink/renderer/modules/cobalt/h_5_vcc.idl
  third_party/blink/web_tests/wpt_internal/cobalt/crash-log/README.md
  third_party/blink/web_tests/wpt_internal/cobalt/crash-log/crash_log_setString.https.any.js
  third_party/blink/web_tests/wpt_internal/cobalt/crash-log/resources/automation.js
  third_party/blink/web_tests/wpt_internal/cobalt/crash-log/resources/fake-crash-annotator-impl.js
Labels: on_device

#4963 Chrobalt ODT gateway: increase start test timeout to 900 sec
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#4965 Update LTS minor version to 60
  cobalt/version.h
Labels: on_device

#4935 Build base_unittests hermetically.
  base/BUILD.gn
  base/allocator/partition_allocator/partition_alloc_unittest.cc
  base/allocator/partition_allocator/shim/allocator_shim_default_dispatch_to_partition_alloc_unittest.cc
  base/allocator/partition_allocator/shim/allocator_shim_unittest.cc
  base/base_paths_posix.cc
  base/debug/stack_trace.cc
  base/files/file_util_unittest.cc
  base/files/important_file_writer_cleaner.cc
  base/process/memory_unittest.cc
  base/profiler/module_cache.cc
  base/test/BUILD.gn
  base/threading/platform_thread_posix.cc
  third_party/fontconfig/include/config.h
  third_party/libevent/BUILD.gn
Labels: on_device

#4972 Chrobalt ODT gateway: rename chrobalt unit test xml files
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#4934 cobalt/browser/metrics: Skeleton CobaltMetricsServiceClient
  cobalt/BUILD.gn
  cobalt/android/BUILD.gn
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.cc
  cobalt/browser/metrics/cobalt_metrics_service_client.h
  cobalt/browser/metrics/cobalt_metrics_service_client_test.cc
Labels: on_device
