Repository youtube/cobalt, pull requests merged in 2025-04, with the labels that each got.

#5256 Update ssl certs
  cobalt/content/ssl/certs/09789157.0
  cobalt/content/ssl/certs/57bcb2da.0
  cobalt/content/ssl/certs/865fbdf9.0
  cobalt/content/ssl/certs/9046744a.0
  cobalt/content/ssl/certs/a89d74c2.0
  cobalt/content/ssl/certs/da0cfd1d.0
  cobalt/content/ssl/certs/f3377b1b.0
  cobalt/network/certs.gni
Labels: on_device

#5255 Ensure GCS buckets are publicly accessible mirrors
  cobalt/media/testing/BUILD.gn
  cobalt/renderer/BUILD.gn
  cobalt/site/docs/development/setup-raspi.md
  components/crx_file/BUILD.gn
  docker/linux/raspi/Dockerfile
  starboard/shared/starboard/player/BUILD.gn
Labels: on_device

#5220 Fix tests not running for linux-eg
  .github/actions/build/action.yaml
  .github/actions/test_targets_json/action.yaml
  .github/workflows/main.yaml
  cobalt/testing/filters/linux-x64x11-evergreen/base_unittests_filter.json
Labels: on_device

#5245 Add performance.getAppStartupTime()
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/StarboardBridge.java
  cobalt/browser/performance/BUILD.gn
  cobalt/browser/performance/performance_impl.cc
  cobalt/browser/performance/performance_impl.h
  cobalt/browser/performance/public/mojom/performance.mojom
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.cc
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.h
  third_party/blink/renderer/core/cobalt/performance/performance_extensions.idl
  third_party/musl/src/starboard/stdlib/strtod_l.c
Labels: cp-26.android

#5244 Remove Unused SOCKADDR_WITH_LENGTH Wrapper for PS5
  starboard/shared/modular/starboard_layer_posix_socket_abi_wrappers.cc
Labels: on_device

#5262 Return if an audio handler isn't created
  cobalt/media/audio/audio_decoder.cc
Labels: cp-26.android

#5334 Disable NSS certificates
  cobalt/build/configs/linux_common.gn
  net/BUILD.gn
  net/cert/internal/system_trust_store_starboard.cc
Labels: on_device

#5330 Reduce spammy logging around test run
  .github/actions/on_device_tests/action.yaml
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#5166 Add support to build cobalt/starboard using an external RDK toolchain
  docker-compose.yml
  docker/linux/rdk/Dockerfile
  starboard/build/config/linux/rdk/starboard_rdk_path.gni
  starboard/build/platforms.py
  starboard/build/toolchain/cobalt_toolchains.gni
Labels: runtest

#5370 Install missing libs and unfilter net_unittests
  cobalt/docker/unittest/Dockerfile
  cobalt/testing/filters/linux-x64x11/net_unittests_filter.json
Labels: on_device

#5402 Update on_device_tests_gateway_client.py
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#5401 ODT gateway: adding test_target name to the results link
  cobalt/tools/on_device_tests_gateway.proto
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#5394 [media] Refine DecoderBufferAllocatorTest
  media/starboard/decoder_buffer_allocator_test.cc
  media/test/data/starboard/allocations_8k.txt
  media/test/data/starboard/allocations_PMwaIrjiz8w.txt
  starboard/tools/media/allocation_extractor.py
Labels: on_device, cp-26.android

#5421 Update DecoderBuffer memory budget on format change
  media/filters/source_buffer_stream.cc
Labels: on_device, cp-26.android

#5412 [media] Optimize DecoderBufferAllocator
  media/starboard/decoder_buffer_allocator.cc
  starboard/common/allocator.h
  starboard/common/reuse_allocator_base.cc
  starboard/common/reuse_allocator_base.h
Labels: on_device, cp-26.android

#5313 Remove invalid rendered frames when calculating dropped frames
  starboard/android/shared/video_frame_tracker.cc
Labels: cp-26.android

#5475 Fix broken web tests configuration
  content/browser/media/session/media_session_impl.cc
Labels: cp-26.android

#5492 [android] Fix crashes on accessing RRO values
  starboard/android/shared/BUILD.gn
  starboard/android/shared/application_android.cc
  starboard/android/shared/application_android.h
  starboard/android/shared/audio_sink_get_min_buffer_size_in_frames.cc
  starboard/android/shared/graphics.cc
  starboard/android/shared/media_get_video_buffer_budget.cc
  starboard/android/shared/runtime_resource_overlay.cc
  starboard/android/shared/runtime_resource_overlay.h
Labels: on_device

#5463 BACKPORT: Pass HTMLMediaElement identifier to ::media::Renderer
  content/public/renderer/content_renderer_client.cc
  content/public/renderer/content_renderer_client.h
  content/renderer/media/media_factory.cc
  content/renderer/media/media_factory.h
  fuchsia_web/webengine/renderer/web_engine_content_renderer_client.cc
  fuchsia_web/webengine/renderer/web_engine_content_renderer_client.h
  third_party/blink/public/platform/web_media_player_client.h
  third_party/blink/renderer/core/dom/node.cc
  third_party/blink/renderer/core/dom/node.h
  third_party/blink/renderer/core/exported/web_media_player_impl_unittest.cc
  third_party/blink/renderer/core/html/media/html_media_element.h
  third_party/blink/renderer/modules/mediastream/webmediaplayer_ms_test.cc
Labels: cp-26.android

#5476 Replace git clones with cached directories
  .github/actions/depot_tools/action.yaml
  .github/actions/on_host_tests/action.yaml
  .github/actions/print_logs/action.yaml
  .github/workflows/main.yaml
Labels: on_device

#5538 [media] Reduce extra copying in MP4StreamParser
  media/formats/mp4/mp4_stream_parser.cc
Labels: on_device

#5532 Call MediaSession.release() before setting to null
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltMediaSession.java
Labels: cp-26.android

#5534 Clean up resolved TODO.
  cobalt/browser/metrics/cobalt_metrics_services_manager_client.cc
Labels: cp-26.android

#5550 Validate param values before reading them
  starboard/android/shared/player_components_factory.h
Labels: cp-26.android

#5569 Merge player_components_factory.cc into .h file
  starboard/android/shared/BUILD.gn
  starboard/android/shared/platform_service.cc
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/player_components_factory.h
Labels: on_device

#5579 Rename player_components_factory.h to .cc
  starboard/android/shared/BUILD.gn
  starboard/android/shared/platform_service.cc
  starboard/android/shared/player_components_factory.cc
Labels: cp-26.android

#5586 [media] Create in_place_reuse_allocator_base.*
  starboard/common/in_place_reuse_allocator_base.cc
  starboard/common/in_place_reuse_allocator_base.h
Labels: on_device, cp-26.android

#5364 Expand ARM test devices and add retries
  .github/actions/on_device_tests/action.yaml
  .github/config/android-arm.json
  .github/workflows/main.yaml
  cobalt/tools/on_device_tests_gateway_client.py
Labels: on_device

#5596 [Cleanup] Remove not-used variables in AudioSink
  starboard/android/shared/audio_track_audio_sink_type.cc
Labels: cp-26.android
