Repository youtube/cobalt, pull requests merged in 2025-07, with the labels that each got.

#6232 Re-enable QueueIntTest.ConcurrentPutAndGet
  cobalt/testing/filters/linux-x64x11/starboard_unittests_wrapper_filter.json
  starboard/common/queue_test.cc
Labels: cp-26.android

#6029 [Refactor] Replace starboard::mutex in starboard/raspi
  starboard/raspi/shared/open_max/dispmanx_resource_pool.cc
  starboard/raspi/shared/open_max/dispmanx_resource_pool.h
  starboard/raspi/shared/open_max/video_decoder.cc
  starboard/raspi/shared/open_max/video_decoder.h
  starboard/raspi/shared/video_renderer_sink_impl.cc
  starboard/raspi/shared/video_renderer_sink_impl.h
Labels: cp-26.android

#6282 Remove Mutex::DCheckAcquired
  starboard/android/shared/drm_system.cc
  starboard/android/shared/media_capabilities_cache.cc
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/video_decoder.cc
  starboard/common/condition_variable.cc
  starboard/common/mutex.cc
  starboard/common/mutex.h
  starboard/nplb/audio_sink_helpers.cc
  starboard/shared/starboard/player/filter/audio_renderer_internal_pcm.cc
  starboard/shared/starboard/player/filter/media_time_provider_impl.cc
Labels: cp-26.android

#6280 Coat: Fix broken builds for cobalt_coat_junit_tests
  cobalt/android/apk/app/src/test/java/dev/cobalt/coat/CobaltActivityTest.java
Labels: cp-26.android

#6274 Import check_op.h (e.g SB_CHECK_EQ) to starboard/ (from base/)
  starboard/android/shared/video_decoder.cc
  starboard/common/BUILD.gn
  starboard/common/check.h
  starboard/common/check_op.cc
  starboard/common/check_op.h
Labels: cp-26.android

#5966 Apply SB_CHECK_EQ and similar macros to more files under starboard/
  starboard/android/shared/audio_sink_min_required_frames_tester.cc
  starboard/android/shared/audio_track_audio_sink_type.cc
  starboard/android/shared/audio_track_bridge.cc
  starboard/android/shared/continuous_audio_track_sink.cc
  starboard/android/shared/decode_target.cc
  starboard/android/shared/drm_system.cc
  starboard/android/shared/file_internal.cc
  starboard/android/shared/input_events_generator.cc
  starboard/android/shared/jni_env_ext.cc
  starboard/android/shared/media_codec_bridge.cc
  starboard/android/shared/media_codec_bridge.h
  starboard/android/shared/media_common.h
  starboard/android/shared/media_decoder.cc
  starboard/android/shared/microphone_impl.cc
  starboard/android/shared/player_components_factory.cc
  starboard/android/shared/video_max_video_input_size.cc
  starboard/android/shared/video_render_algorithm.cc
  starboard/shared/starboard/player/player_internal.cc
Labels: cp-26.android

#6309 Decouple content/shell/gpu and content/shell/utility
  cobalt/shell/BUILD.gn
  cobalt/shell/app/shell_main_delegate.cc
  cobalt/shell/app/shell_main_delegate.h
  cobalt/shell/gpu/DEPS
  cobalt/shell/gpu/shell_content_gpu_client.cc
  cobalt/shell/gpu/shell_content_gpu_client.h
  cobalt/shell/utility/DEPS
  cobalt/shell/utility/shell_content_utility_client.cc
  cobalt/shell/utility/shell_content_utility_client.h
Labels: cp-26.android

#6299 [Cleanup] Remove pthread/types_internal.h
  starboard/shared/pthread/thread_sampler_internal.cc
  starboard/shared/pthread/types_internal.h
Labels: cp-26.android

#6290 [Cleanup] Remove starboard/socket.h and related files.
  starboard/CHANGELOG.md
  starboard/common/BUILD.gn
  starboard/common/socket.cc
  starboard/common/socket.h
  starboard/common/socket_test.cc
  starboard/elf_loader/exported_symbols.cc
  starboard/nplb/extern_c_test.cc
  starboard/nplb/include_all.c
  starboard/nplb/posix_compliance/posix_socket_helpers.h
  starboard/nplb/socket_wrapper_test.cc
  starboard/socket.h
Labels: cp-26.android

#6378 Decouple cobalt/shell/app from content shell
  cobalt/shell/BUILD.gn
  cobalt/shell/app/DEPS
  cobalt/shell/app/app-Info.plist
  cobalt/shell/app/app.icns
  cobalt/shell/app/framework-Info.plist
  cobalt/shell/app/helper-Info.plist
  cobalt/shell/app/ios-Info.plist
  cobalt/shell/app/ios/resources/BUILD.gn
  cobalt/shell/app/ios/resources/LaunchScreen.storyboard
  cobalt/shell/app/ios/resources/ic_back.imageset/Contents.json
  cobalt/shell/app/ios/resources/ic_back.imageset/ic_back.png
  cobalt/shell/app/ios/resources/ic_back.imageset/ic_back_2x.png
  cobalt/shell/app/ios/resources/ic_back.imageset/ic_back_3x.png
  cobalt/shell/app/ios/resources/ic_forward.imageset/Contents.json
  cobalt/shell/app/ios/resources/ic_forward.imageset/ic_forward.png
  cobalt/shell/app/ios/resources/ic_forward.imageset/ic_forward_2x.png
  cobalt/shell/app/ios/resources/ic_forward.imageset/ic_forward_3x.png
  cobalt/shell/app/ios/resources/ic_menu.imageset/Contents.json
  cobalt/shell/app/ios/resources/ic_menu.imageset/ic_menu.png
  cobalt/shell/app/ios/resources/ic_menu.imageset/ic_menu_2x.png
  cobalt/shell/app/ios/resources/ic_menu.imageset/ic_menu_3x.png
  cobalt/shell/app/ios/resources/ic_reload.imageset/Contents.json
  cobalt/shell/app/ios/resources/ic_reload.imageset/ic_reload.png
  cobalt/shell/app/ios/resources/ic_reload.imageset/ic_reload_2x.png
  cobalt/shell/app/ios/resources/ic_reload.imageset/ic_reload_3x.png
  cobalt/shell/app/ios/resources/ic_stop.imageset/Contents.json
  cobalt/shell/app/ios/resources/ic_stop.imageset/ic_stop.png
  cobalt/shell/app/ios/resources/ic_stop.imageset/ic_stop_2x.png
  cobalt/shell/app/ios/resources/ic_stop.imageset/ic_stop_3x.png
  cobalt/shell/app/ios/shell_application_ios.h
  cobalt/shell/app/ios/shell_application_ios.mm
  cobalt/shell/app/resource.h
  cobalt/shell/app/shell.rc
  cobalt/shell/app/shell_content_main.cc
  cobalt/shell/app/shell_content_main.h
  cobalt/shell/app/shell_crash_reporter_client.cc
  cobalt/shell/app/shell_crash_reporter_client.h
  cobalt/shell/app/shell_main.cc
  cobalt/shell/app/shell_main_delegate.cc
  cobalt/shell/browser/shell.cc
  cobalt/shell/browser/shell_platform_delegate_ios.mm
Labels: cp-26.android

#6146 [POSIX] Disable multi-process functions
  .github/actions/on_host_tests/action.yaml
  base/BUILD.gn
  base/process/launch_starboard.cc
  cobalt/build/testing/targets/linux-x64x11/test_targets.json
  cobalt/testing/filters/linux-x64x11/blink_unittests_filter.json
  cobalt/testing/filters/linux-x64x11/cc_unittests_filter.json
  components/viz/test/test_in_process_context_provider.cc
  mojo/core/BUILD.gn
  mojo/core/embedder_unittest.cc
  mojo/core/message_pipe_unittest.cc
  mojo/core/message_unittest.cc
  mojo/core/platform_wrapper_unittest.cc
  mojo/core/shared_buffer_unittest.cc
  mojo/public/cpp/bindings/tests/receiver_unittest.cc
  mojo/public/cpp/system/tests/BUILD.gn
  starboard/tools/api_leak_detector/evergreen/manifest
Labels: lightweight

#6386 Remove unsupported platforms from cobalt/shell/app
  cobalt/shell/app/shell_content_main.cc
  cobalt/shell/app/shell_content_main.h
  cobalt/shell/app/shell_crash_reporter_client.cc
  cobalt/shell/app/shell_crash_reporter_client.h
  cobalt/shell/app/shell_main.cc
Labels: cp-26.android

#6419 BACKPORT: Fix securityexception in Android U devices that impedes loc…
  build/android/gtest_apk/java/src/org/chromium/build/gtest_apk/TestStatusReceiver.java
Labels: cp-26.android

#6453 decode_target_context_runner: Remove extra namespace closing braces
  starboard/shared/starboard/decode_target/decode_target_context_runner.cc
  starboard/shared/starboard/decode_target/decode_target_context_runner.h
Labels: outside collaborator

#6473 cleanup: Remove unmatched namespace closing brackets
  starboard/android/shared/input_events_generator.cc
  starboard/shared/deviceauth/deviceauth_internal.cc
  starboard/shared/deviceauth/deviceauth_internal.h
  starboard/shared/libaom/aom_library_loader.h
  starboard/shared/libaom/aom_video_decoder.cc
  starboard/shared/libaom/aom_video_decoder.h
  starboard/shared/speechd/speechd_internal.cc
  starboard/shared/speechd/speechd_internal.h
Labels: cp-26.android

#6399 media: Allow StarboardRenderer to RequestOverlayInfo from WebMediaPlayer
  media/mojo/clients/starboard/starboard_renderer_client.cc
  media/mojo/clients/starboard/starboard_renderer_client.h
  media/mojo/clients/starboard/starboard_renderer_client_factory.cc
  media/mojo/clients/starboard/starboard_renderer_client_unittest.cc
  media/mojo/mojom/renderer_extensions.mojom
  media/mojo/services/starboard/starboard_renderer_wrapper.cc
  media/mojo/services/starboard/starboard_renderer_wrapper.h
  media/starboard/starboard_renderer.cc
  media/starboard/starboard_renderer.h
  media/starboard/starboard_renderer_unittest.cc
Labels: cp-26.android

#6352 Register the signal handlers in Starboard
  cobalt/app/cobalt_switch_defaults_starboard.cc
  starboard/build/config/BUILDCONFIG.gn
  starboard/linux/shared/BUILD.gn
  starboard/linux/x64x11/BUILD.gn
  starboard/linux/x64x11/main.cc
  starboard/linux/x64x11/run_starboard_main.cc
  starboard/nplb/posix_compliance/posix_signal_test.cc
  starboard/nplb/posix_compliance/posix_sleep_test.cc
  starboard/nplb/posix_compliance/posix_thread_kill_test.cc
  starboard/nplb/posix_compliance/posix_usleep_test.cc
  starboard/raspi/2/BUILD.gn
  starboard/raspi/shared/BUILD.gn
  starboard/raspi/shared/main.cc
  starboard/raspi/shared/run_starboard_main.cc
  starboard/tools/symbolize/symbolize.py
Labels: runtest

#6426 Use embedded v8 snapshot for linux
  build/config/ozone_extra.gni
  cobalt/build/configs/android_common.gn
  cobalt/build/configs/common.gn
  cobalt/build/modular_executable.gni
  starboard/build/buildflags.gni
  v8/gni/snapshot_toolchain.gni
Labels: runtest

#6512 Disable failing cobalt_browsertests
  cobalt/testing/browser_tests/navigation_browsertest.cc
Labels: cp-26.android

#6460 Use a copy of ContextLifecycleObserver for exit notifications
  third_party/blink/renderer/platform/context_lifecycle_notifier.cc
Labels: cp-26.android

#6574 Delay adding SurfaceView to after Browser init
  cobalt/android/BUILD.gn
  cobalt/android/apk/app/src/main/java/dev/cobalt/coat/CobaltActivity.java
  cobalt/android/apk/app/src/test/java/dev/cobalt/coat/MockShellManagerNatives.java
  cobalt/android/apk/app/src/test/java/dev/cobalt/coat/ShellManagerTest.java
  cobalt/shell/android/browsertests/src/org/chromium/content_shell/browsertests/ContentShellBrowserTestActivity.java
  cobalt/shell/android/java/src/dev/cobalt/shell/Shell.java
  cobalt/shell/android/java/src/dev/cobalt/shell/ShellManager.java
Labels: cp-26.android

#6436 Fix path to elf_loader_sandbox in loader script
  .github/actions/upload_test_artifacts/action.yaml
  cobalt/build/archive_test_artifacts.py
  cobalt/build/modular_executable.gni
  starboard/build/util/generate_runfile.py
Labels: on_device

#6385 [Starboard] Add Starboard Features Extension for Android TV
  cobalt/browser/BUILD.gn
  cobalt/browser/cobalt_content_browser_client.cc
  cobalt/common/features/BUILD.gn
  cobalt/common/features/features.cc
  cobalt/common/features/features.h
  cobalt/common/features/starboard_features_initialization.cc
  cobalt/common/features/starboard_features_initialization.h
  starboard/android/shared/BUILD.gn
  starboard/android/shared/features_extension.cc
  starboard/android/shared/features_extension.h
  starboard/android/shared/system_get_extensions.cc
  starboard/extension/feature_config.h
  starboard/extension/features.h
  starboard/shared/starboard/feature_list.cc
  starboard/shared/starboard/feature_list.h
  starboard/shared/starboard/features.cc
  starboard/shared/starboard/features.h
Labels: cp-26.android
